### ISSUE TITLE
Issue with webpage access

### ISSUE THREAD

**Issue by shbrief** [pepkit/pephub#101]
Hi! I'm trying to check https://pephub.databio.org/, hopefully for some pephub documentation. But I'm getting this error:
```
{
detail: "The token has expired, please log in again."
}
```
Can someone help me with this? Thanks!

**Comment by nleroy917** [comment]
Hi @shbrief !

This is a known bug.. See #57. I believe we have a fix for this in the pipeline, hopefully to be released soon.

**In the meantime**, you can solve this by just deleting your cookies for the site.
- In chrome: https://support.google.com/chrome/answer/95647?hl=en&co=GENIE.Platform%3DDesktop
- In firefox: https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox

**Comment by shbrief** [comment]
@nleroy917 Thanks!

**Comment by shbrief** [comment]
Btw, is there any documentation/tutorial on how to use pephub?

**Comment by khoroshevskyi** [comment]
> Btw, is there any documentation/tutorial on how to use pephub?

Right now we have only documentation how to set up pephub localy and unfortunately we don't have any documentation(help) for pephub website.

---
@nleroy917 @nsheff 
I think it will be usefull to add documentation/map/help of pephub for users who start using pephub. Good example is quick start with hello world on GitHub: https://docs.github.com/en/get-started/quickstart/hello-world

**Comment by nleroy917** [comment]
This should be fixed in the latest release
