### ISSUE TITLE
Saving fails in production

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#102]
### Overview of behavior
In public, production deployment of pephub, saving a configuration file fails with `Network error`. I cannot reproduce this locally in development. The request fails immediately.

### Steps to reproduce
1. Navigate to [pephub.databio.org](https://pephub.dtabio.org)
2. Login
3. Navigate to a project/PEP edit page
4. Click the "Project Config" tab
5. Add simple attribute (e.g. `name: test`)
6. Click save
7. Observe network error

### Additional context
In the console, I can see this error:
```
Blocked loading mixed active content “http://pephub.databio.org/api/v1/projects/nleroy917/basic/?tag=default”
```

I wonder if it's because I am calling the `http` URL and not the `https` version.

**Comment by nsheff** [comment]
"mixed content" usually means some http/https interaction.

**Comment by nleroy917** [comment]
That's what I saw too. However, I'm using relative paths for all my api requests... (e.g. `/api/v1/...`)

**Comment by nleroy917** [comment]
Interestingly, these other requests **do not work in production:**
- `DELETE` a project from your namespace page
- `PATCH` a project's meta-meta data (description, name, etc)

But, the **do work in production:**
- `POST` a new PEP to your namespace

So what is unique about the `DELETE` and `PATCH` endpoints versus the `POST` endpoints?

**Comment by nleroy917** [comment]
A pattern I've noticed is that the two API calls **not working**, are simple `ajax` requests:

`fetch(..., { method: "PATCH"})`

While the `POST` method to create a new PEP is actually the result of a form submission. I wonder if this is the discrepancy. ~~The search API call (which is also `ajax` and a `POST`) **does** work. This one is different in that it specifies a content-type in the header (`application/json`). Maybe if I add those headers to the other calls, it will fix things. Hard to say since I can only reproduce in production.~~ Nevermind, the `PATCH` requests include these too, I just didn't see them.

**Comment by nleroy917** [comment]
I've removed any trailing slashes from `POST`, `PATCH`, and `DELETE`, requests. Further evidence that maybe the trailing slash is the issue... the `POST` endpoint for creating a new PEP **did not** have a trailing slash and was one of the only ones that worked in production.

**Comment by nleroy917** [comment]
This looks to be solved now after the latest release
