### ISSUE TITLE
Public example

### ISSUE THREAD

**Issue by johnyaku** [pepkit/pephub#103]
Is there a public-facing  instance of pephub where I can search public PEPs?

Trying to assess whether it will be worth the trouble of installing our own instance, and a working example would be helpful.

**Comment by johnyaku** [comment]
I think I may have just answered my own question.
For example: https://pephub.databio.org/geo_recent/GSE193912?tag=raw

**Comment by nleroy917** [comment]
Hi @johnyaku you are correct. [pephub.databio.org](https://pephub.databio.org) is a public instance we've launched.

@Khoroshevskyi can provide more info, but I believe we have ~10,000 PEPs from GEO in there.

**Comment by khoroshevskyi** [comment]
Hi! Now in database we have already more then 27 000 projects. Most of this projects were populated from GEO, nevertheless we already have some users projects.

The best way to find sample projects is to use pephub search. e.g. https://pephub.databio.org/search?query=leukemia

Moreover you can check this simple example: https://pephub.databio.org/Khoroshevskyi/example?tag=test

**Comment by johnyaku** [comment]
Thanks! I'll check it out, but I'm having trouble opening the links.
```
{"detail":"The token has expired, please log in again."}
```
But I can't navigate back to the login page without seeing this message.

**Comment by nleroy917** [comment]
Yes, this is a known issue... See https://github.com/pepkit/pephub/issues/101#issuecomment-1450102001

@Khoroshevskyi can we get a hotfix out for this? You said you fixed it, correct?

**Comment by johnyaku** [comment]
That fixed it -- thanks! (Altho ultimately a redirect would be more user-friendly...)

And I can see the examples that you linked to. Thanks again!
