### ISSUE TITLE
documentation/tutorial on how to use pephub

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#106]
Right now we have only documentation how to set up pephub locally and unfortunately we don't have any documentation(help) for pephub website.

I think it will be usefull to add documentation/map/help of pephub for users who start using pephub. Good example is quick start with hello world on GitHub: https://docs.github.com/en/get-started/quickstart/hello-world

_Originally posted by @Khoroshevskyi in https://github.com/pepkit/pephub/issues/101#issuecomment-1451147392_

**Comment by nleroy917** [comment]
~~This is added to the milestone, are we still doing this? I don't see us having time for this before release tomorrow.~~

Nvm, this wasn't on the milestone.

**Comment by nsheff** [comment]
this is low priority.

**Comment by khoroshevskyi** [comment]
This issue was solved in v0.11.0
