### ISSUE TITLE
Don't connect to server for help

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#111]
```
pephub --help
[INFO] [22:33:56] Initializing connection to pephub...
[INFO] [22:33:56] Connected successfully!
...
```

for `--help` or `--version` or if someone just types `pephub`, there should be no reason to connect to anything first. Connect only if the person requests something that requires a connection.

**Comment by nleroy917** [comment]
This is obsolete now that we are dropping the `cli` See #112.

**Comment by nsheff** [comment]
Ok. I didn't realize, but I think that's better. So there should be no more CLI.
