### ISSUE TITLE
use VersionInHelpParser

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#112]
It's nice to show the version in the default `--help` menu.

```
pephub --help
[INFO] [22:33:56] Initializing connection to pephub...
[INFO] [22:33:56] Connected successfully!
usage: pephub [-h] [-V] {serve} ...

pephub - PEP web server

positional arguments:
  {serve}
    serve        run the server

options:
  -h, --help     show this help message and exit
  -V, --version  show program's version number and exit

For subcommand-specific options, type: 'pephub <subcommand> -h' https://github.com/pepkit/pepserver
```

For this, use ubiquerg's VersionInHelpParser

**Comment by nleroy917** [comment]
This issue might be obsolete now that we decided to just default to Docker + uvicorn deployment, right?

**Comment by nsheff** [comment]
just default to that, or make that the only option?

Is there no more `pephub` command ? If so, then this is obsolete and you can close it.

**Comment by nleroy917** [comment]
The cli [still exists](https://github.com/pepkit/pephub/blob/439fd53ffea6199c39fbd091a486aeb7ae09e917/pephub/main.py#L89), but it hasnt been testing nor maintained. I also think documentation for the `cli` is gone, so we can remove that + those dependencies

- [ ] Remove any `cli` requirements
- [ ] Remove `main()` from `pephub/main.py`
- [ ] Ensure documentation is up to date.

**Comment by nsheff** [comment]
closing in favor of #155
