### ISSUE TITLE
search links don't do anything

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#113]
![image](https://user-images.githubusercontent.com/5271009/224016318-2f878eed-79fc-493b-8184-3c09ccd89492.png)

On the production server, when I click on these links, nothing happens.

**Comment by nleroy917** [comment]
They look disabled. If the number of results returned is less than the limit, these are set to disabled. This is directly related to the whole "score-threshold" thing we discussed. That is, if you set a low enough score, you can in theory paginate forever.

Perhaps we don't render the pagination UI at all if `limit > len(results)`, and instead put something like "Looking for more results? Try lowering your score threshold".

Just an idea.

**Comment by nleroy917** [comment]
This might also be obsolete with the interface updates
