### ISSUE TITLE
Privacy error [URGENT]

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#117]
I have private project in pephub: `Khoroshevskyi/GSE131026:test_geo`. 
If I am not logged in, from views I don't have permission to this project (and I don't see it), however, if I am using endpoint I can download.
e.g. 
API:
https://pephub.databio.org/api/v1/projects/Khoroshevskyi/GSE131026/samples?tag=test_geo
PEPHub UI:
https://pephub.databio.org/Khoroshevskyi/GSE131026?tag=test_geo

![image](https://user-images.githubusercontent.com/41573628/225767091-0ff9059f-d7f4-4599-bc8d-cc579c81b779.png)

@nleroy917

**Comment by nleroy917** [comment]
I'm unable to reproduce this. Locally, at least. I haven't tried with the production deployment.

**Comment by khoroshevskyi** [comment]
you can just check this project here using localhost: http://localhost:8000/api/v1/projects/Khoroshevskyi/GSE131026/samples?tag=test_geo

**Comment by nleroy917** [comment]
Yeah, I see that. I dont know why privacy protections on my local build and production are out of sync - I'm on master locally. Maybe something was changed recently that didn't get pulled into prod. Hopefully, with the next release (device auth 🙂) things get fixed?

**Comment by khoroshevskyi** [comment]
I just checked it on my local branch. And additionally created new project + made it private. Have the same issue.
I am using the latest changes (pulled from master) + my changes

**Comment by khoroshevskyi** [comment]
Update: I have checked our API, and  we didn't add user checking functionality to any of our project endpoints.

**Comment by nleroy917** [comment]
I'm pretty sure we do? [This line](https://github.com/pepkit/pephub/blob/ccdcd817173d5c4e6102c7e4df03d32a022f0ccb/pephub/routers/api/v1/project.py#L30) checks if a user can read the current requested project.

```python
def verify_user_can_read_project(
    project: str,
    namespace: str,
    tag: Optional[str] = DEFAULT_TAG,
    project_annotation: AnnotationModel = Depends(get_project_annotation),
    session_info: Union[dict, None] = Depends(read_authorization_header),
    orgs: List = Depends(get_organizations_from_session_info),
):
    """
    Authorization flow for reading a project from the database.

    See: https://github.com/pepkit/pephub/blob/master/docs/authentication.md#reading-peps
    """
    if project_annotation.is_private:
        if session_info is None:
            # raise 404 since we don't want to reveal that the project exists
            raise HTTPException(
                404, f"Project, '{namespace}/{project}:{tag}', not found."
            )
        elif any(
            [
                session_info.get("login") != namespace
                and namespace
                not in orgs,  # user doesnt own namespace or is not member of organization
            ]
        ):
            # raise 404 since we don't want to reveal that the project exists
            raise HTTPException(
                404, f"Project, '{namespace}/{project}:{tag}', not found."
            )
```

**Comment by khoroshevskyi** [comment]
@nleroy917  we have some API links in project page. Can we open that links with additionally sending header with requests?

**Comment by nleroy917** [comment]
I dont think so... I guess that's a downside to the UI. They are really there for demonstration/information purposes only. I  never intended for them to be a primary source of info.

**Comment by nleroy917** [comment]
Maybe instead of directly linking to the data, we can just provide `curl` examples. Something like:

```
curl -X GET \
  --header "Authorization: Bearer <access-token>" \
   "https://pephub.databio.org/api/v1/projects/..."
```
