### ISSUE TITLE
Return `401` error for JWT expiration

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#120]
Right now, the server simply ignores the JWT if it is expired, but we should probably respond more appropriately. It might make more sense to return `HTTPException` with a `401` response.

**Comment by khoroshevskyi** [comment]
I guess it should be HTTPException 498
![](https://http.cat/498)

**Comment by nleroy917** [comment]
Unfortunately, I don't think that's a supported code. It looks specific to the ArcGIS, software. [Wikipedia has](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Unofficial_codes) a comprehensive list.

**Comment by nleroy917** [comment]
This should be solved in the latest release

**Comment by nleroy917** [comment]
According to @khoroshevskyi this isnt solved yet - we should look into this more.

**Comment by nleroy917** [comment]
I believe that this is solved. At least the UI can handle `401`s fine right now.

**Comment by nleroy917** [comment]
### Discussed June 27th, 2023
- we need to make sure we are distinguishing between a `401` (Unauthenticated) v a `403` (Unauthorized).
- go through codebase to make sure that we are properly returning these codes

**Comment by nleroy917** [comment]
This is resolved in the `0.9.x` release
