### ISSUE TITLE
Schema-specific validation on PEP edit page

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#127]
Right now, it's possible to validate a PEP on the edit page, but only against the general PEP schema.

It would be important to be able to specify a schema for a PEP, and then validate against a specific schema.

Maybe the schema could be specified as a registry path in the PEP metadata tab.

**Comment by nleroy917** [comment]
I don't think the `eido` endpoints are mature enough to handle this right now. Schema's are often represented as files, and that doesn't integrate well with the JAM-stack, database representations we use now. I think it would be worth a discussion for handling this.

**Comment by nsheff** [comment]
what do you mean? Isn't this already possible?

**Comment by nsheff** [comment]
@ayobi -- after reminding myself how eido is  working, it looks like the eido package itself will have no problem with this, you can pass a dict (things don't have to be represented as files). So, this should be a simple change in the end points to use eido slightly differently. Should be a quick fix.

**Comment by ayobi** [comment]
This is now possible in release `0.9.x`
