### ISSUE TITLE
Groups of PEPs

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#129]
It would be nice to somehow create a collection of PEPs and then release/version these as a unit.

**Comment by khoroshevskyi** [comment]
How do we define group of PEPs? 
- What is it? 
- Can user create group of peps only using own peps, or he can use Peps from other namespaces? 

- Do we connect group of peps to specific namespace? If yes, then I would suggest to create new user table, that will store information about namespaces

**Comment by ayobi** [comment]
#74 would essentially be grouping peps from different namespaces

**Comment by nsheff** [comment]
Here is a proposal. First, a series of points as background:

- Sometimes I need a PEP of PEPs. A PEP of PEPs is a PEP where each sample (each row in the table) points to a PEP.
- A PEP of PEPs could be called a POP for short. Remember, a POP *is a* PEP. It's a special kind of PEP. So, all POPs are PEPs, but not all PEPs are POPs.
- A group of PEPs is almost the same as a POP. But it's not really the same thing, since a group of PEPs is really just a list of PEPs. A POP, on the other hand, provides more functionality... I could annotate each PEP with a column in the table. I could add POP-level information in the config file. A POP also inherits all the preprocessing capability of a PEP, since it *is* a PEP.
- Another nice thing about a POP is that, because it *is* a PEP, we could actually just use PEPhub to store POPs. In fact, I can already do this. I just create a new PEP, and add a column called `registry_path`. Now, I point to whatever PEPs I want in my group. In this way, PEPhub already supports POPs, since they are PEPs.

Now, I'll explain the how we could build some infrastructure to make POPs even more useful.

What if we actually recognize POPs in PEPhub as a special kind of PEP, with added functionality? The UI could allow you to toggle "POP functionality" the same way you can toggle "Private". We could add a column to the `project` table, or add a new table containing a list of PEPs with POP functionality enabled.

Now, for any PEP with POP functionality enabled, we could do a few things:
- add in a new tab alongside `Config` and `Sample table` that would provide an interface to "Add a PEP to this POP". This would do nothing more than provide a simple interface exactly like the one that currently allows you to attach a schema to a PEP, except you could add a PEP from PEPhub to this POP.
- all that interface has to do is add a new sample row, with the corresponding registry path in the `registry_path` column.
- it could also provide a list of current PEPs (sample rows) in the POP, with a delete button to remove them.
- the user could also edit the list of PEPs in the POP by just editing the sample table and adding rows, or whatever.
- I could then imagine a new POP-specific interface that basically just lists links to the PEPs contained within a given POP -- it could behave basically the same way the current `/namespace` view endpoint works, but just only listing the PEPs in that POP. This would allow you to have a page showing a list of PEPs that don't necessarily belong in the same namespace. It would only work for PEPs flagged with POP functionality.

Conclusion:

This proposal is very easy to implement, since it just re-uses all the PEP functionality for groups of PEPs. There's something appealing about this recursion to me, even if it takes a minute to get your head around. It would just be adding a few simple UI additions, and a small database change.

The POPs would then automatically benefit from the privacy and ownership tools already built into PEPs (for example. you could have an organization-level POP that anyone in your org could add to. Or, you could have a private POP. This would be already done). It also will make the POPs magically benefit from any PEP-based version/release system we develop.

**Comment by ayobi** [comment]
Speaking about this today in the infrastructure meeting, I think there were some conflicts as to the best approach in implementing this from a database perspective. From what was communicated from @khoroshevskyi he has made progress on a version of grouping PEPs that is a little different than what you described @nsheff. I think you guys have discussed some of this already but if he wants to clarify on here so we have a better paper-trail that'd be nice.

**Comment by nleroy917** [comment]
I think we are close to having this implanted, right @khoroshevskyi ?

**Comment by khoroshevskyi** [comment]
Group of PEPs are now POP. In pepdbagent, everything was implemented

**Comment by khoroshevskyi** [comment]
This issue was solved in v0.11.0
