### ISSUE TITLE
`eido/validator` seems broken?

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#13]
I can't get this endpoint to return anything. I'm getting a `404`.

**Comment by nsheff** [comment]
it works. try it through the web validator:
http://pephub.databio.org/eido/validator/validator.html

you can look at the javascript there to see how to POST to that endpoint.

**Comment by nleroy917** [comment]
I see. `/eido/validator/` gives the `404`. 

`eido/validator/validator.html` works for me.

**Comment by nsheff** [comment]
yeah, `/eido/validator/` isn't anything. The endpoint is `/eido/validate`.

http://pephub.databio.org/docs
