### ISSUE TITLE
Versioning ideas

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#130]
How should we handle versioning?

Right now you could sort of version with tags, but there isn't really a great interface to do this. 

It might be useful to have a "save under different tag" interface. 

Or, is there the idea of a "commit" ?

**Comment by khoroshevskyi** [comment]
Maybe we should group projects with different tags by name. And then in namespace visualize them as one project, but add pop-up button where you can choose specific tag and enter project page. Projects with the same name can be ordered by last update date (in pop up button). By default, user will enter project with the most recent update date.

I think it's pretty easy to implement this approach and I think it can be used also as project versioning

**Comment by nleroy917** [comment]
An idea that was brought up at one point was just creating a new table called "history" or something and then each time a `PATCH` is made to the server, we just dump out the config and sample table(s) as they existed into that table as a row with a timestamp. Then we can render a UI that lets people look through these "commits" or change history and revert to one or view it if they wish.

**Comment by nsheff** [comment]
# Idea for versioning pephub

We want to be able to keep track of versions. Every change would be too much...We could keep track of every change for awhile (say, 30 days), purge anything older than that, but allow users to "snapshot" a point in time to make it permanent. You could then "select a previous version", which could be *any* change in the last 30 days, or any snapshot previous to that.

Here's some brainstorming on how to accomplish this:

- create a new table that looks exactly like the sample table, but is called `sample_history`
- do the same for projects, `project_history`
- whenever a sample changes, copy the old sample, with a timestamp, into `sample_history` first, *then* make the change in the primary table as currently done
- similarly, whenever a project changes, copy the old project into `project_history`, then make the change in the primary table.
- provide a "revert changes" or "history" UI interface that shows recent changes, ordered by timestamp. Allow user to click on a change to "restore previous version". This would copy the relevant entries from such and such time point into the primary table.
- add an additional table called 'snapshot'. it has a `project_id`, `timestamp`, and `tag` (or `snapshot_name`) columns.
- Add a `snapshot` endpoint and UI button. When a user clicks `snapshot`, it creates a new history entry, just like a 'save'. It *also* adds a row to the 'snapshot' table pointing to this current project.
- periodically purge the history table of any samples greater than 30 days old that lack an entry in the 'snapshot' column.

**Comment by nleroy917** [comment]
This should mostly be addressed with #349
