### ISSUE TITLE
Add capability for adding and editing subsample tables

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#131]
- [x] Add backed endpoint for editing subsample tables
- [x] Add UI for editing subsample tables

p.s.
in raw peppy `subsample_dict` is a list (I probably named it incorrectly🫥) So we can have more then one subsample table.

**Comment by nleroy917** [comment]
I am close on this, but @khoroshevskyi, I'm getting a weird error from `peppy` when sending the subsample table data:

```python
subsample_df = pd.DataFrame.from_dict(updated_project.subsample_table)
subsample_df_json = subsample_df.to_dict()

new_raw_project[SUBSAMPLE_RAW_DICT_KEY] = subsample_df_json
 new_raw_project[CONFIG_KEY] = current_project.config.to_dict()

new_project = Project().from_dict(new_raw_project)

>>> ValueError('DataFrame constructor not properly called!')

**Comment by khoroshevskyi** [comment]
Can you pull my changes from the https://github.com/pepkit/pephub/tree/new_pepdb_with_description ? It should solve this issue

**Comment by khoroshevskyi** [comment]
Now, UI has only one subsample table. What if project will have multiple subsample tables? I think it's not high priority, but it would be nice to think about this issue

**Comment by khoroshevskyi** [comment]
Issue was partially solved. Subsample creation and modification on the UI was added (for one subsample table). Closing this, and opening separate issue: #208
