### ISSUE TITLE
Assign schemas to PEPs

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#137]
This is related to #94. Wouldn't it be cool if when creating a PEP (or uploading a PEP), one could assign it to a specific schema? Something like this:

![image](https://user-images.githubusercontent.com/41063083/232827735-fd7e64bc-f83f-46e9-9dc2-7ac8b055b9d4.png)

This would require updates to a few packages, but I think could be super powerful. One could then filter/search for PEPs on those compatible with the given schema. It would also really enhance the metadata builder UI.

**Comment by khoroshevskyi** [comment]
I think at this point, I would do restructuring of the database...
I think so because there is few things that we would have to add:
1) Create new table for project (It can improve efficiency).
2) Add grouping of peps.
3) Add favorite projects.
4) Forking history (forking will be happening in pepdbagent)

**Comment by nleroy917** [comment]
This could just be another table called project-schemas and each row is just a schema that the project is tagged to. Four columns:

1. Namespace
2. Project
3. Tag
4. Schema

New row per schema tagged to that project. I don't disagree with your statement about the database needing restructuring, but this should be pretty easy to implement! Low priority, just an idea 🤷🏻‍♂️

**Comment by nleroy917** [comment]
From the discussion in meeting (**May 02, 2023**):
- Create an ultra-thin wrapper around `schema.databio.org` to programmatically grab schemas. (#147)
- If you want to submit a schema, make PR against repo and merge.
- Need method to grab a list of all available schemas.
- Need a table that stores schemas.
- Need a method to grab the `yaml` from a particular schema
- `pepdbagent` *might* need to be updated for this.

**Comment by ayobi** [comment]
So now that we have the schemas available via schema.databio.org/list.json I made a component in pephub that grabs them to populate a dropdown and put that in create and upload a schema. It looks like this:

<img src="https://github.com/pepkit/pephub/assets/17304717/31caf234-6e3c-4a9f-a049-403e23b19721" width=50% height=50% alt="Screenshot from 2023-06-05 14-07-41">

**Comment by nsheff** [comment]
looks cool, but will this scale? or how will you change it if there are hundreds of available schemas?

**Comment by nleroy917** [comment]
Is this native `<select>`? Can we use [`react-select`](https://react-select.com/home) instead of that? It lets you filter through search/auto-complete. I'm already using it for some components.

**Comment by ayobi** [comment]
ah thanks, that's much better @nleroy917 
<img src="https://github.com/pepkit/pephub/assets/17304717/b4d47fd6-c884-44d9-8516-0a6e43097ad9" width=50% height=50% alt="Screenshot from 2023-06-05 14-07-41">

**Comment by nleroy917** [comment]
In `pepdbagent`:
**With upload:**
```python
agent.create(
    ...
    pep_schema = 'random_schema_name'
    ...
)
```
**With edit:**
```python
agent.update(
    ...
    update_dict={
        'pep_schema': 'random_schema_name'
     }
    ...
)
```

**Comment by nleroy917** [comment]
Schemas can now be assigned with latest update
