### ISSUE TITLE
brainstorm pephubclient source link + add copy link button to pephub

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#138]
1) maybe we should change our client to something like this: git clone git@github.com:databio/ffff.git
so pephubclient will have: pep pull pep@pephubclinet.databio.org/Khoroshevskyi:__/00 or something similar... 

2) Add copy link on pephub page

**Comment by nleroy917** [comment]
Would be nice to implement something similar to dockerhub:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/41063083/233180419-b4202632-71de-4626-bfe7-f3f94cc70292.png">

**Comment by nsheff** [comment]
`pephub.databio.org://<namespace>/<registry>`

**Comment by khoroshevskyi** [comment]
@nsheff 
if protocol has dots inside `.`, then ubiquerg returns None. Is it correct behavior, or is it bug ?
I would like to use link (string) like this:  `pephub.databio.org://Khoroshevskyi/looper:default` or `pephub.databio.org::Khoroshevskyi/looper:default`

**Comment by nsheff** [comment]
hm, I think this is a ubiquerg bug because I think periods should be allowed in the protocol name.
could fix in this line: https://github.com/pepkit/ubiquerg/blob/1d79b7c2d2e2319b3221b30cf63ccb377ac1fbc4/ubiquerg/paths.py#L50

**Comment by khoroshevskyi** [comment]
@nleroy917 @ayobi 
copy link button still should be added to the pephub

**Comment by nleroy917** [comment]
@khoroshevskyi still want this?

**Comment by nleroy917** [comment]
<img width="1235" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/bf5cf48e-ed81-4b0a-9323-798c3c42d1be">

**Comment by khoroshevskyi** [comment]
This issue was solved in v0.11.0
