### ISSUE TITLE
schema.databio.org interface update

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#147]
Related to comment posted by @nleroy917 in https://github.com/pepkit/pephub/issues/137#issuecomment-1531883446

Create an ultra-thin wrapper around `schema.databio.org` to programmatically grab schemas. Follow the rough approach used by https://github.com/databio/mm_templates.

it should provide
- a list endpoint to provide a list, with description and registry path, for all available schemas.
- a nicer user-browsable interface. these could include links to the validation page for the schema at pephub.

**Comment by nsheff** [comment]
Include instructions: "If you want to submit a schema, make PR against repo and merge."

**Comment by nleroy917** [comment]
### Notes from meeting 05/16/2023
- for now, assign one schema per PEP
- need API endpoint where I can hit `/schemas` and return a list of all available schemas that can be used in PEPhub
- we need to repeat what was done on the `markmeld` repo.

**Steps:**
1. Create `index_contents.py` that will create a `.json` file that represents all items in `schema.databio.org`. You can reference it [here](https://github.com/databio/mm_templates/blob/master/index_contents.py).
2. ~~Create a `git` hook that runs `python index_contents.py > list.json` for us on commit.~~
2. Create GitHub action that will run this script when commits are made to master. It will push the `list.json` to this repo.. Here is an example of something that does something similar: [link](https://github.com/databio/region_embeddings_paper/blob/main/.github/workflows/build-sciquill-manuscript.yaml)
4. Create a nice user interface (`index.html`), that will have embedded javascript that hits the endpoint created in the previous step that produces some `html` that looks pretty.

**Comment by ayobi** [comment]
This is complete, here's the [index](http://schema.databio.org/) and the repository with the github [action](https://github.com/databio/schema.databio.org) 
I'll make a few changes to make the list output by namespace

**Comment by nsheff** [comment]
looks great!

**Comment by ayobi** [comment]
Added the description from the schema yaml file to the description of the schemas in the list. Before with markmeld it would fill in the description via a separate README file. The schema yaml files have a decent description so I fed it that so it would have at some description rather than a `null`.

**Comment by nsheff** [comment]
that makes sense to me!

**Comment by ayobi** [comment]
Added which project the schema belongs to in the list http://schema.databio.org/ 
I think this is looking good enough to close out now :+1:
