### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#15]
Just so I don't forget --

We need to look into performance of peppy. It takes too long to process/return a large project. It needs to be very fast.

- @nleroy917 said it's processing twice, this needs to be reduced to once
- might need to explore peppy code a bit to see if we can optimize.

**Comment by nsheff** [comment]
@nleroy917 did you already address this in #14 ?

**Comment by nleroy917** [comment]
No, but I was reading more about it and I think I have a way to prevent double-loading peps. You can return objects from FastAPI dependencies. It might look like this:

```python
@router.get("/", summary="Fetch a PEP")
async def get_pep(namespace: str, pep_id: str, pep: peppy.Project = Depends(verify_pep(pep_id)):
    """
    Fetch a PEP from a certain namespace
    """
    proj = peppy.Project(_PEP_STORES[namespace][pep_id])
    return {
        "pep": proj
    }
```

Inside the validation function you need to `yield` the object you want to return... I think

**Comment by nleroy917** [comment]
Ok, I committed changes to only validate once. If you're curious... This is the code:

```python
def validate_pep(namespace: str, pep_id: str):
    try:
        yield peppy.Project(_PEP_STORES[namespace][pep_id])
    except NotImplementedError as nie:
        raise HTTPException(status_code=400, detail=f"Error loading PEP. {nie}")
```

yielding the object returns it to your decorated function for the route or endpoint.

**Comment by nsheff** [comment]
Not sure I understand completely, but it appears you're validating the project when a PEP is retrieved.

I think this is inefficient. It results in validating the project every time someone requests the data. What's the point?

Instead, validation should be run at submission or editing.

**Comment by nleroy917** [comment]
That's true. I guess that indicates there should be no server-side validation at all then? Just assume they are all valid?

**Comment by nsheff** [comment]
The validation should happen in a github action.


This would be in the repo with the peps (not this, the pephub software repo), and looks like it's been addressed: https://github.com/pepkit/pephub.databio.org/issues/3

**Comment by nleroy917** [comment]
I think this has been improved substantially. PEPs are no longer being processed twice. And, I think the latest `peppy` release addressed some things too.

**Comment by nsheff** [comment]
Ok it seems we've addressed the main aspects of this, and the upstream peppy performance issues is now here: https://github.com/pepkit/peppy/issues/387
