### ISSUE TITLE
Add links to GEO, PMID, etc

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#150]
I've been using pephub as a search engine recently to find relevant datasets since it's indexed descriptions are pretty good at finding things I need.

Some things I wish it had:
1. A direct link to the accession on GEO
2. A direct link to the pub-med ID

**Comment by nsheff** [comment]
so, more generally... what if:

1. we add  a `links` section in the pep project config file, and pephub would parse these links and produce links to whatever you want.
2. we update geofetch to automatically add to the pep links to geo and for any attached publications.

then users could also add their own links

**Comment by khoroshevskyi** [comment]
Yeah, I like that Idea:)

**Comment by nleroy917** [comment]
I also like that idea. Then you can add more links by editing your project config file using the editor.

**Comment by nleroy917** [comment]
it was also discussed that we should add the ability to render markdown in the description of the PEP.

**Comment by nleroy917** [comment]
Feedback welcome:
![ph-markdown](https://github.com/pepkit/pephub/assets/41063083/0353986a-443c-4599-aabf-e62fd37de13c)

**Comment by nleroy917** [comment]
It was decided that with markdown, no additional implementation is needed for adding links. therefore, this is likely solved.
