### ISSUE TITLE
Remove CLI remnants 

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#155]
The cli [still exists](https://github.com/pepkit/pephub/blob/439fd53ffea6199c39fbd091a486aeb7ae09e917/pephub/main.py#L89), but it hasnt been testing nor maintained. I also think documentation for the `cli` is gone, so we can remove that + those dependencies

- [x] Remove any `cli` requirements
- [x] Remove `main()` from `pephub/main.py`
- [x] Ensure documentation is up to date.

We determined that it makes more sense to run this application as a typical fastAPI approach instead of writing and maintaining a CLI. So, we should remove all CLI-related code.

_Originally posted by @nleroy917 in https://github.com/pepkit/pephub/issues/112#issuecomment-1580838027_

**Comment by nleroy917** [comment]
I've removed the `cli` remnants, and this should be solved.
