### ISSUE TITLE
sample table column order is not preserved

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#162]
The sample table MUST preserve the column order of the input table. Right now it is not doing so.

**Comment by nleroy917** [comment]
@khoroshevskyi can you chime in? I know in the past you've seemed to understand why this occurs. I think this is a weird quirk of `peppy` and/or `pandas`. It **always** wants to put `sample_name` last. Some things after investigation. I was trying to submit this to the server:

<p align="center">
<h4 align="center"> Intended order: <code>fastq_1</code> > <code>sample_name</code> > <code>fastq_2</code> </h4>
</p>

![image](https://github.com/pepkit/pephub/assets/41063083/aea33f59-ce79-4281-996c-75d538cb097c)

### I've stepped through the `PATCH` endpoint on the server to make a change to a PEP

**1. The correct order reflected on the UI gets sent to the server:**


``` python
# /api/v1/project.py - Line 109
updated_project.sample_table_csv
'fastq_1,sample_name,fastq_2,\nsample1_R1.fastq.gz,sample1,sample1_R2.fastq.gz,\nsample2_R1.fastq.gz,sample2,sample2_R2.fastq.gz,\nsample3_R1.fastq.gz,sample3333,sample3_R2.fastq.gz,'
# ^^^^ note the order of the header
```

**2. `pandas` initially reads it in fine:**

```python
# api/v1/project.py - Line 116
sample_table_df
               fastq_1 sample_name              fastq_2
0  sample1_R1.fastq.gz     sample1  sample1_R2.fastq.gz
1  sample2_R1.fastq.gz     sample2  sample2_R2.fastq.gz
2  sample3_R1.fastq.gz  sample3333  sample3_R2.fastq.gz
```

**3. The `new_raw_project` object seems to get created just fine:**
```python
# api/v1/project.py - Line 149
new_raw_project['_sample_dict']
'fastq_1':
{0: 'sample1_R1.fastq.gz', 1: 'sample2_R1.fastq.gz', 2: 'sample3_R1.fastq.gz'}
'sample_name':
{0: 'sample1', 1: 'sample2', 2: 'sample3333'}
'fastq_2':
{0: 'sample1_R2.fastq.gz', 1: 'sample2_R2.fastq.gz', 2: 'sample3_R2.fastq.gz'}
```

**4. `peppy` seems to have no trouble preserving that order:**
```python
# api/v1/project.py - Line 149
new_project = Project().from_dict(new_raw_project)
new_project.sample_table
                         fastq_1 sample_name              fastq_2
sample_name                                                      
sample1      sample1_R1.fastq.gz     sample1  sample1_R2.fastq.gz
sample2      sample2_R1.fastq.gz     sample2  sample2_R2.fastq.gz
sample3333   sample3_R1.fastq.gz  sample3333  sample3_R2.fastq.gz
```

**5. Order is even preserved after being consumed by `pepdbagent`'s flow:**
```python
# pepdbagent/modules/project.py - Line 364
update_values = self.__create_update_dict(update_values)
update_values['project_value']['_sample_dict']
'fastq_1':
{'sample1': 'sample1_R1.fastq.gz', 'sample2': 'sample2_R1.fastq.gz', 'sample3333': 'sample3_R1.fastq.gz'}
'sample_name':
{'sample1': 'sample1', 'sample2': 'sample2', 'sample3333': 'sample3333'}
'fastq_2':
{'sample1': 'sample1_R2.fastq.gz', 'sample2': 'sample2_R2.fastq.gz', 'sample3333': 'sample3_R2.fastq.gz'}
```

**6. REFETCHING CAUSES LOSS OF ORDER:**
```python
# api/v1/project.py - Line 182
raw_peppy_project = agent.project.get(namespace, project, tag=tag, raw=True)
raw_peppy_project['_sample_dict']
'fastq_1':
{'sample1': 'sample1_R1.fastq.gz', 'sample2': 'sample2_R1.fastq.gz', 'sample3333': 'sample3_R1.fastq.gz'}
'fastq_2':
{'sample1': 'sample1_R2.fastq.gz', 'sample2': 'sample2_R2.fastq.gz', 'sample3333': 'sample3_R2.fastq.gz'}
'sample_name':
{'sample1': 'sample1', 'sample2': 'sample2', 'sample3333': 'sample3333'}
```

Note how the column order is no longer preserved. Seems like something happens inside `pepdbagent` when projects are fetched.

**Comment by nleroy917** [comment]
Something is alphabetizing the columns. Attempting to create the following:

![image](https://github.com/pepkit/pephub/assets/41063083/68702f6b-d228-4411-a4c2-d3f0b2adb2e1)

Yields this:

![image](https://github.com/pepkit/pephub/assets/41063083/5e5ce025-dd20-432e-9cdf-139564b6479c)

**Comment by khoroshevskyi** [comment]
I looked into this issue, and find out that postgresql is changing the order. I tried to fined solution or work around for this issue, but couldn't find any. I am not sure if we can solve this drawback

**Comment by nsheff** [comment]
You can use 'json' instead of 'jsonb'. It is less efficient, but preserves the text representation as I understand it.

**Comment by khoroshevskyi** [comment]
Fixed!
