### ISSUE TITLE
It's not clear how to add a schema

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#163]
![image](https://github.com/pepkit/pephub/assets/5271009/506e5407-c8ca-46db-ac18-28523915e74c)

My project says "No schema", but I don't see how to add one.

**Comment by nsheff** [comment]
~~I also don't see how I can edit the project description.~~

I see now, you have to be logged in. That was not immediately apparent to me... but I figured it out.

**Comment by nleroy917** [comment]
We could maybe grey out the gear icon if they aren't logged in and just render a tooltip telling them to log in to add schema.

**Comment by nleroy917** [comment]
It seems clear enough
