### ISSUE TITLE
Error messages could be better

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#164]
Right now, the error messages propagated to the UI are cryptic and not really informative. An example:

![image](https://github.com/pepkit/pephub/assets/41063083/1e68aa06-acb7-414b-870d-17492f42ee58)

While this isn't necessarily a bug, it's poor UX. We should display better error messages to the user if things fail. Two things:

- [x] Make sure the server sends predictable responses for errors (i.e. do we add a `message` for server errors?)
- [x] Make sure the client handles these properly. I envision this happening in the `useQuery` or `useMutation` hooks. I already do this for any JWT errors and 401 responses. Here is an example where I catch these unauthorized responses:

```ts
const mutation = useMutation({
    mutationFn: () => handleSubmit(onSubmit)(),
    onSuccess: () => {
      resetForm(
        {}, // not sure why this works, but it does.
        {
          keepValues: true,
        },
      );
      toast.success('Project metadata updated successfully.');
      queryClient.invalidateQueries([namespace, name, tag]);
      onSuccessfulSubmit();

      // if newTag or newName is different, redirect to new project
      if (newTag !== tag || newName !== name) {
        window.location.href = `/${namespace}/${newName}?tag=${newTag}`;
      }
    },
    onError: (error: AxiosError) => {
      // check for axios 401
      if (error.response?.status === 401) {
        toast.error('You are not authorized to edit this project.');
        return;
      }
      toast.error(`There was an error updated project metadata: ${error}`);
      onFailedSubmit();
    },
  });
```

**Comment by nleroy917** [comment]
I'm got some code sitting on my dev branch right now where we can add some global error handling things. It's sitting in the [PageLayout](https://github.com/pepkit/pephub/blob/6dab8cffd8a761eedc1599d8807051311fc5df26/web/src/components/layout/page-layout.tsx) component (there is a reason for this which I can explain). You can just add error handling to the `onError` property of the `QueryClient`:

```tsx
const queryClient = useQueryClient();

// set default options for all queries
queryClient.setDefaultOptions({
  queries: {
    onError: (error: any) => {
      // check if axios error
      // if so, check if 401
      if (error.response && error.response.status === 401) {
        logout(); // just deletes the token
      }
    },
  },
});
```

**Comment by nleroy917** [comment]
So, while the `setDefaultOptions` is nice, I think we can just go into each `useMutation`/`useQuery` hooks and specify `onError` handling for the really important ones.

I think we need to **ensure** we have error handling with proper toasts for the following actions:
- [x] Adding a PEP
- [x] Deleting a PEP
- [x] Updating a PEP (clicking save)
- [x] Forking a PEP

For each of the above actions, do the following:
1. Go to the corresponding endpoint and look for proper server logic error handling. Should be of the form `raise HTTPException(status_code=400, ...). If it is **not** there, add it. Then
2. Use the server error handling and responses to inform the creating of `onError` events. Should look something like:

```ts
onError: (error: AxiosError) => {
  // check if axios error
  // if so, check if 401
  if (error.response && error.response.status === 400) {
    const message = error.response.message
    toast.create(`${message}`); // something like this, syntax might be off
  }
},
```

**Comment by ayobi** [comment]
in v0.9.6

**Comment by khoroshevskyi** [comment]
Messages are still not the best. I want to upload PEP, but getting internal server error, and I don't know what's wrong with that pep...
![image](https://github.com/pepkit/pephub/assets/41573628/394b4f99-69a4-4426-8a39-d04cca72366b)

**Comment by nleroy917** [comment]
I think there are two things to this:
1. identifying where we are sending error-prone requests to the server, and
2. coming up with a response schema that the server sends which is expected by the UI. 

The first is easy, but the second always seems to give trouble for some reason. I think we just need to agree on a data scheme that needs to be sent back from the server each time an error occurs, that way the UI knows what to expect and can render helpful message when necessary. For example:
```json
{
  "message": "The PEP has an invalid project_modifier: ...",
  "code": 400,
  ...
}
```

Something like that. At the end of the day, someone needs to just sit down and do this, and then test with various PEPs

**Comment by nleroy917** [comment]
To help standardize this, I did a few things:
1. Whenever there is an error, raise an `HTTPException`, this has a `detail=""` argument which we can extract out
2. All mutations/API-calls that mutate data, have an `onError` handler that specifically looks for this `detail` keyword in the server response.

**Some examples:**
<img width="520" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/6ec6ce85-0019-4622-b337-f8c621ef26fe">
<img width="520" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/d7045af8-b436-40a2-89b5-43dc01206c76">
<img width="520" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/2feea192-7414-494d-84d7-1392fc65db1b">

**Comment by nleroy917** [comment]
I think that this is implemented. So long as the server raises an HTTPException with `detail`
