### ISSUE TITLE
Add more endpoints

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#17]
I thought it would be efficient to have a list of all endpoints we should have for pephub in an issue. This is what I have so far:

- [x] `/<namespaceid>/<projectid>`
- [x] `/<namespaceid>/<projectid>`
- [x] `/<namespaceid>/<projectid>/config`
- [x] `/<namespaceid>/<projectid>/samples`
- [x] `/<namespaceid>/<projectid>/samples/<sampleid>`
- [x] `/<namespaceid>/<projectid>/subsamples/<sampleid>`
- [x] `/<namespaceid>/<projectid>/zip`

@nsheff Feel free to add more that you see as necessary.

**Comment by nsheff** [comment]
This looks like a good start. We may have others in the future but I think these are the basics.

**Comment by nleroy917** [comment]
For `.../data/ endpoints`... what does that entail? Since it's just the **metadata**, we aren't actually going to return data files... but is it the `sample_table` that gets returned?

**Comment by nsheff** [comment]
Those were from the dataconnect standard, right? Remember our "levels of data" ? For the purposes of PEP, "data" is what we'd call metadata from the project perspective.

**Comment by nleroy917** [comment]
Notes from infrastructure meeting:

- We should try to follow some of the conventions of data connect
- Later we can open up endpoints that will comply with the data-connect specification.

**Comment by nleroy917** [comment]
Re: the `/<namespace>/><projectid>/zip` endpoint, what's the best way to zip up a pep?

**Comment by nsheff** [comment]
For now maybe just putting the yaml and csv files into a .zip folder?
