### ISSUE TITLE
Repopulate GEO data

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#171]
After fixing the order issue (#162), we need to repopulate all the data from GEO currently in the database to correct order for existing stuff.

Wait for: 
- [x] https://github.com/pepkit/geofetch/issues/119
- [x] geofetch v 0.12.3 (with order preserving fixed)
- [x] https://github.com/pepkit/metageo_pephub/issues/13
- [x] pepdbagent0.5.1
- [x] fix https://github.com/pepkit/metageo_pephub

**Comment by khoroshevskyi** [comment]
~We are ready to repopulate GEO. Example of project, that preserves order, and has link in the description: https://pephub.databio.org/geo/GSE51132?tag=raw~

11.07.2023 Update: We are not ready

**Comment by khoroshevskyi** [comment]
Database was repopulated
