### ISSUE TITLE
Should fork should copy existing project description?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#172]
Right now, the fork interface defaults description to emptyt:

![image](https://github.com/pepkit/pephub/assets/5271009/cdd51478-2d61-4401-8c6b-cbfcecf5865f)

**Comment by nleroy917** [comment]
<img width="749" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/da469d0f-2e24-43a1-ae4f-59c7692149a1">

Probably, this is what GitHub does

**Comment by nleroy917** [comment]
I think that this made it in with the `0.8.4`, so this should be solved
