### ISSUE TITLE
Forking a project leads to Error page

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#173]
Whenever I fork a project, I get forwarded to this page:

![image](https://github.com/pepkit/pephub/assets/5271009/fb6f2ad1-7c1c-4713-bc61-dee48d47c497)

it seems if I click "take me back", that the fork worked... so the error message is just incorrect.

**Comment by nleroy917** [comment]
Can't reproduce this, do you have a project you are trying to fork I can try? Maybe its a bug sitting on production that was fixed.

**Comment by nsheff** [comment]
it was true of any project.

**Comment by nleroy917** [comment]
I can't reproduce this, so I think it was a production bug that is now fixed.

**Comment by ayobi** [comment]
Forking is working in release `0.9.x`
