### ISSUE TITLE
GEO project sample_name is an FTP link

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#174]
Why in the GEO project is the sample_name an FTP link?

![image](https://github.com/pepkit/pephub/assets/5271009/8dc52b55-81f7-47a1-b25b-eed9028e429c)

https://pephub.databio.org/geo/GSE141232?tag=raw

**Comment by nleroy917** [comment]
This is a duplicate of #151 I think and it's all resolved with changes sitting on master. It was an issue with the way we parsed samples on the client (via `csv` instead of `JSON`)

**Comment by nleroy917** [comment]
@nsheff can you check this one again with the latest release?

**Comment by nsheff** [comment]
yes it works now
