### ISSUE TITLE
Forking changes a project name to lowercase

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#175]
When I forked this project:

https://pephub.databio.org/geo/GSE141232?tag=raw

the new one was renamed to lowercase in my namespace:

![image](https://github.com/pepkit/pephub/assets/5271009/4a651eb4-43f0-4e09-9bf9-95aea05ba409)

This is confusing to me. I was expecting it to copy the same project name from the original.

**Comment by khoroshevskyi** [comment]
it is fixed now. All the project are lowercase now
