### ISSUE TITLE
Bug with CSV parsing of embedded commas in table fields

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#176]
This project is taking embedded commas and causing that to split into different columns, so the column headers are off.

Example: https://pephub.databio.org/geo/GSE141232?tag=raw

See how "sample_library_strategy" is Toubia" -- the last name of the sample_contact_name in the original, since it had 2 commas for some reason in the original geo SOFT file for this accession.

![image](https://github.com/pepkit/pephub/assets/5271009/d33c1223-1b71-4aad-aec0-618869fb2ce7)

I think the big picture is just some kind of test to either prevent commas in fields, or deal with them appropriately.

If I try to write: `a,b,c`, handsontable changes that to `"a`.

**Comment by nleroy917** [comment]
Yeah this is also fixed with updates according to #151 

**locally:**
<img width="575" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/5c5a8f2f-13e8-4532-a61b-2551989872dc">

**Comment by nleroy917** [comment]
@nsheff Can you retry now with the latest release?
