### ISSUE TITLE
Navigation suggestions: redesign dropdowns for 2 elements?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#177]
In 2 places, pephub uses dropdown menus to reveal menus with only 2 options.

![image](https://github.com/pepkit/pephub/assets/5271009/614107e1-96a7-4cee-b857-f7c278b645d0)
![image](https://github.com/pepkit/pephub/assets/5271009/5b06fe5c-377a-4039-9653-6000f4d54eae)

I find it frustrating to have to click into dropdowns so frequently when there aren't that many options. For me, I think dropdowns are useful, but only if there are, say, 3 or more options. If there are just 2 options, that's few enough to just put them there straight up, no menu required.

### For the "Edit project" Menu

- maybe put "fork" and "download" into this menu?
- or, just take "edit" and "delete" out of the menu (my preference -- we have plenty of space)

### For the "Profile" Menu:

I would like if there were a link that would take me to the "My PEPs" page with one click. This could be solved with either:

1. remove the dropdown with "My PEPs" and logout, promoting these unhidden links
2. Make the "PEPhub" link (and home page?) default to My PEPs if I'm logged in. There's nothing valuable on the main page anyway, except a one-click unhidden link to "My PEPs" (which is where you'd be anyway), and a "validation" link to the universal validator"

If we do option 2, we should move the "Validation" link to the header or footer. It should probably be there anyway, really.

**Comment by ayobi** [comment]
This is now in release `0.9.x`
