### ISSUE TITLE
Navigation suggestion: button groups

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#178]
Right now we are using independent buttons in rows, like these:

![image](https://github.com/pepkit/pephub/assets/5271009/80116434-494e-42ee-8cf2-b81c034f4ffc)
![image](https://github.com/pepkit/pephub/assets/5271009/4832ebbb-3880-4336-9892-73b830cb7e91)
![image](https://github.com/pepkit/pephub/assets/5271009/ba51895a-6846-4df5-bb0f-e3769fd6eefd)

Furthermore, these have different styling/size/color that don't seem to have a justification.

I have 3 suggestions:

1. I think these will look nicer using bootstrap [button groups](https://getbootstrap.com/docs/5.3/components/button-group/#button-toolbar).

They look like this:

![image](https://github.com/pepkit/pephub/assets/5271009/cba8c040-f7ca-41c2-a966-f97cbd05d900)

2. I would suggest using a consistent style/color theme of some kind.

Finally, should these two independent button rows be merged into a single button group toolbar?

![image](https://github.com/pepkit/pephub/assets/5271009/cd8d3e67-ad0e-4038-b1d9-8c587ce28517)

If not, does this grouping really make sense?

Row 1:
- download
- api endpoints
- fork
- pencil
  - edit project
  - delete

Row 2:
- valid?
- save
- discard

To me this grouping/hierarchy is not logical/intuitive. Some thoughts:

- some of these tools apply to the Project, and others apply to the sample table. How could we indicate that? Does it make sense to divide into two groups on that criterion? Would API Endpoints be split?
- "Edit project" is really for the description/metadata -- the "config" is also in some sense the project. So that's a bit confusing.

**Comment by nleroy917** [comment]
Thanks @ayobi  for implementing this

#### I like this change:
<img width="1327" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/024bcf6c-5b1b-4334-a1ec-7a74845a8500">

#### But I don't think I like this change:
<img width="639" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/40b4dc87-0013-4065-a280-5908dcd857c1">

**Comment by ayobi** [comment]
We came to a compromise and refined the buttons, this is now in release `0.9.x`
