### ISSUE TITLE
Proposal to change the sample table repreesntation

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#186]
It seems like there are two competing representations of the sample table across pephub. The first is a **list of objects** which takes a row-first view. The second is an **object of objects** which takes a column-first view.

#### Given the example table:
| sample_name | genome | path |
|------------|------------|------------|
| sample1    | hg38   | data/s1.fastq.gz    |
| sample2   | hg38    | data/s2.fastq.gz    |
| sample3    | hg38    | data/s3.fastq.gz    |

#### We can represent it as a list of objects:
```json
[
  {
    "sample_name": "sample1",
    "genome": "hg38",
    "path": "data/s1.fastq.gz"
  },
  {
    "sample_name": "sample2",
    "genome": "hg38",
    "path": "data/s2.fastq.gz"
  },
  {
    "sample_name": "sample3",
    "genome": "hg38",
    "path": "data/s3.fastq.gz"
  }
]
```

#### or, an object of objects:
```json
{
  "sample_name": {
    "1": "sample1",
    "2": "sample2",
    "3": "sample3"
  },
  "genome": {
    "1": "hg38",
    "2": "hg38",
    "3": "hg38"
  },
  "path": {
    "1": "data/s1.fastq.gz",
    "2": "data/s2.fastq.gz",
    "3": "data/s3.fastq.gz"
  }
}
```

There is conflict among the codebase where we represent sample tables using both of these representations. Namely, the *getters* (`GET /api/v1/projects/nleroy917/basic123/samples`) overwhelmingly return the first option (list of objects). While, the *setters* (`POST /api/v1/nleroy917`) seem to expect the latter representation (object of objects). I would like these to be consistent across the application since it can make development a tad frustrating having to accommodate both.

I'm going to argue for the first representation for a few reasons:
1. Many client-side libraries expect data to be in this form
2. It takes a "sample-first" approach where we think of things as a list of samples, not a list of sample attributes
3. Its just more intuitive. People think of tables as rows of data, not columns of data. The "list of objects" representation supports this mindset.

This is low-priority, but it would be nice to be consistent at the end of the day. Open to discussion.

**Comment by nleroy917** [comment]
### Discussed June 27th, 2023
- it was decided that we will store samples and subsamples in the database in the `records` format. That is, `[{column -> value}]` See this issue: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html
- Alex will update the database for this, and then the UI should be easier to develop.

**Comment by nleroy917** [comment]
@khoroshevskyi is this solved?

**Comment by khoroshevskyi** [comment]
We introduced new pep sample representation - records (list of objects), and changes were mainly done in peppy (v0.35.6)
