### ISSUE TITLE
Config file contains incorrect description and name 

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#188]
When I am downloading zip file, PEP config stores description and name that was provided there, or it is empty. 
Config file should contain description and name that were provided in pephub.

This issue is mainly related to downloading zip PEPs.

**Comment by khoroshevskyi** [comment]
Should be fixed in https://github.com/pepkit/pepdbagent/pull/86

**Comment by nleroy917** [comment]
@khoroshevskyi was this resolved?

**Comment by khoroshevskyi** [comment]
Yes, this issue is solved in pepdbagent0.5.0
