### ISSUE TITLE
Standardize return package schema/format

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#19]
@nsheff As I work on these endpoints, I am just returning raw data with nothing else. For example this is the API response for `/pep/demo/subsample1/config`:

```
pep_version: "2.0.0"
sample_table: sample_table.csv
subsample_table: subsample_table.csv
looper:
  output_dir: $HOME/example_results
```

It's the config file in `yaml`, but nothing else. Should we be standardizing the return data packages? Something like...

```json
{
  "status": "ok",
  "message": "success",
  "data": {
    "pep_version": "2.0.0",
    "sample_table": "sample_table.csv",
    "subsample_table": "subsample_table.csv",
    "looper": {
      "output_dir": "$HOME/example_results"
    }
  }
}
```

Does FastAPI have a way to standardize responses, sort of how it has a way to standardize request handling (with dependencies, route prefixes, etc)?

**Comment by nsheff** [comment]
I have mixed feelings about this. I like the simplicity of just returning the thing exactly as it is... this will make it easier to, for example, ingest the output of pephub in a client like peppy or pepr.

However, I also like the appeal of using JSON here like you suggest.

What do you think of providing a ?format=x query parameter to alternate between these two?

**Comment by nleroy917** [comment]
This also seems outdated and we also have sort of standardized a return format for a lot of things:

```json
{
    "items": [...],
    "limit": 20,
    "offset": 0,
    "count": 100
}
```
