### ISSUE TITLE
PEP isn't valid after changing sample table

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#197]
I noticed a weird bug: when I upload a PEP, change its schema to render it **invalid**, then change the sample table to comply with the schema, the validation indicator doesn't render a "✅ Valid" mark.

#### Steps to repododuce
1. Submit a new blank PEP using the default params
2. Edit your PEP to use the `pipelines/pepatac` schema
3. View validation errors
4. Change sample table to comply with validation errors
5. Save project
6. Observe that the validation indicator hasn't changed

My suspicion is that the `useValidation` query isn't refiring. I'm nearly positive that it's because we arnt invalidating the cached `useValidation` hook when projects update. It should be an extremely simply fix

**Comment by ayobi** [comment]
Should be good now with v0.9.2
