### ISSUE TITLE
Providing file formats with eido conversions

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#2]
Eido provides a CLI to convert a PEP into different output formats: http://eido.databio.org/en/latest/filters/

pephub should provide an API to retrieve sample metadata in various formats by specifying an eido filter.

Thus we should provide:

1. an endpoint to list available filters. That just basically runs `eido filter` (obviously from within python, not on the CLI)
2. and endpoint that takes a PEP identifier (registry path), plus a filter name, and returns the data in that format. That's basically running `eido convert config.yaml -f <filter>`.

**Comment by nleroy917** [comment]
Would this fit into your `eido` endpoints?

**Comment by nsheff** [comment]
yes, this should be part of eido, can build off the ones I've already written.

**Comment by nleroy917** [comment]
I think this is actually possible: https://pephub.databio.org/api/v1/docs#/project/convert_pep_api_v1_projects__namespace___project__convert_get
