### ISSUE TITLE
Render github image for namespaces

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#201]
To visually distinguish namespace pages, it would be nice to render the avatar for the corresponding Github user and/or organization. Luckily, we can do this on the fly for any organization or user even if they haven't logged in with pephub. GitHub will redirect to the avatar of a user/org if you simply add `.png` to the end of their github link: https://stackoverflow.com/a/36380674/13175187

Therefore, on the namespace page we can simply add an `<img />` tag like so:

```tsx
<img
  src={`https://github.com/${namespace}.png`}
  width={...}
  height={...}
/>
```

I think this would be a nice touch, but is low priority.

**Comment by nleroy917** [comment]
Adding this to the list of organizations in the upper right dropdown would look great as pointed out by @ayobi.

#### A mockup:
![image](https://github.com/pepkit/pephub/assets/41063083/cd9f7fa1-5356-4ce2-aeaa-cb30fbba075f)

**Comment by ayobi** [comment]
Added to version 0.9.2
