### ISSUE TITLE
Bug in create project

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#206]
![image](https://github.com/pepkit/pephub/assets/5271009/54129c51-1e51-4c32-ae1e-8fa802dc66eb)

I'm trying to create a project. I'm using a different index column (not `sample_name`). It won't let me create it.

Also, this error message is confusing.

**Comment by nleroy917** [comment]
This is - I think - caused by the same thing as #207

**Comment by ayobi** [comment]
fixed in v0.9.5
