### ISSUE TITLE
can't change sample_name column

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#207]
When I try to change the name of the column called `sample_name`, I get:

![image](https://github.com/pepkit/pephub/assets/5271009/94b67c0e-7e32-48c3-a305-68f6df83e744)

**Comment by nleroy917** [comment]
Related: #164

**Comment by khoroshevskyi** [comment]
1) First issue is in peppy.from_dict()
2) Second issue is https://github.com/pepkit/pephub/blob/aa3aadee18d35ee2add4e50ac20215ca59ac3969/pephub/routers/api/v1/project.py#L156-L172
3) ... (probably there is more issues)

**Comment by khoroshevskyi** [comment]
This error should be partially fixed after:
- https://github.com/pepkit/peppy/pull/453
- https://github.com/pepkit/pephub/commit/24be8a9329d3e2517796a2e2a48edd44c6ae0bfb

Update of the project that has not default index is impossible due to UI. Project config and sample + subsample should be updated simultaneously, otherwise peppy will rise an error. (Now Frontend is sending 3 separate update requests to update project. Everything should be happening in one Post request.) @ayobi @nleroy917

**Comment by nleroy917** [comment]
Yeah this will definitely need a UI update. Should be a quick fix, though. We need to merge the three mutations `useProjectConfigMutation`, `useSampleTableMutation`, etc into one. 

I suggest keeping these for other potential use, but we need merge functionality and make a new one that can handle it all at once.

**Comment by nleroy917** [comment]
@khoroshevskyi is right - it is a UI problem.

**Right now we do something like this:**
```ts
// onSave handler
if (sampleTableIsChanged) {
  // run sample table update code
}
if (configIsChanged) {
  // run config update code
}
if (subSampleTableIsChanged) {
  // run subsampletable update code
}
```
**When we should be doing something like this:**
```ts
// onSave handler
if(anythingIsChanged) {
  // run everything update code
}
```

The code for the "run everything" should just be a big `useMutation` hook that will accept as optional params: `config`, `sampleList`, `subSampleList` - and then call the server sending all three at once. I suggest something like:

```ts

interface ProjectUpdateParams {
  config?: string
  sampleList?: Sample[]
  subSampleList?: Sample[]
}

export const useProjectUpdateMutation(namespace: string, name: string, tag: string, jwt: string, params: ProjectUpdateParams) {
    return useMutation({
      mutationFn: () => updateProject(namespace, name, tag, jwt, params),
      onSuccess: ...,
      onError: ...
    })
}

// etc etc etc
```
