### ISSUE TITLE
Make PEPhub mobile friendly

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#211]
### Motivation
[A sizable chunk](https://explodingtopics.com/blog/mobile-internet-traffic#mobile-internet-top-stats) of internet traffic comes from mobile devices. Many sources cite mobile traffic as the majority. TailwindCSS (a very popular CSS library) is designed to be ["mobile-first"](https://tailwindcss.com/docs/responsive-design). While users of PEPhub are more likely to be desktop power-users, it would be nice to have a decent landing page that looks good on mobile in case someone stumbles on it while browsing the web.

### Proposal
The landing page right now is a mess on any mobile device:

<img src="https://github.com/pepkit/pephub/assets/41063083/0d19f1be-90b0-44df-b967-812f1704038b" height="400px" alt="PEPhub landing page" />

While I don't think we need to support mobile devices on the pages that contain real data/functionality, a good looking landing page for iPhones, Androids, etc would be a nice thing. Simply altering some of the bootstrap classes to use [breakpoints](https://getbootstrap.com/docs/5.2/layout/breakpoints/) should suffice.

**Comment by nsheff** [comment]
+1 for "I don't think we need to support mobile devices on the pages that contain real data/functionality" and
+1 for "a good looking landing page for iPhones, Androids, etc we be a nice thing. Simply altering some of the bootstrap classes should suffice."

**Comment by nleroy917** [comment]
I believe that the landing page is (mostly) mobile friendly
