### ISSUE TITLE
Landing page design

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#212]
Even though the "PEP on the main page" was a good idea, the old landing page was much better.

Some specific issues with the current landing page:

- now it's this long spread out thing in the middle of the page, with vertical whitespace before and after
- the sample table is way bigger than it needs to be, with a bunch of empty rows, and column widths that don't make sense.
- there's no color or anything visual

I think it looks quite poor on my machine:

![image](https://github.com/pepkit/pephub/assets/5271009/c841106b-8738-48a9-9e26-3a6435d6cd43)

Definitely needs work.

Kinda related to #211.

**Comment by nsheff** [comment]
it seems like we lost the container that kept it from spreading itself out horizontally. Look how the footer bar doesn't match the content anymore.

**Comment by nsheff** [comment]
What do you think of putting the example in the `databio` namespace? Otherwise whoever has the 'example' namespace on github can change this.

How about pointing it at `databio/example` ?

**Comment by nleroy917** [comment]
> What do you think of putting the example in the databio namespace? Otherwise whoever has the 'example' namespace on github can change this.

Yeah, I agree. `example/landing` was my idea since the `example` user on GitHub looks abandoned. I think Alex can easily change it on the backend.

**Comment by nleroy917** [comment]
I think this was solved with the latest release.
