### ISSUE TITLE
why is this endpoint 'forks' instead of 'fork' ?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#215]
![image](https://github.com/pepkit/pephub/assets/5271009/ea5ef387-b8ab-406a-aed4-d563258c0f18)

**Comment by nleroy917** [comment]
I think because [that's how GitHub did it](https://docs.github.com/en/rest/repos/forks?apiVersion=2022-11-28), so I copied them. They think of a fork as an object or a "thing"

**Comment by nsheff** [comment]
ok.
