### ISSUE TITLE
PEPhub fails for large PEPs

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#225]
I was trying to upload a very large sample table. It had >75,000 samples, with 1875(I think?) attributes per sample. The file was ~325 megabytes.

PEPhub responded with this toast message:
<img src="https://github.com/pepkit/pephub/assets/41063083/e7dd2250-c8de-4fec-96f2-87948dc9951b" width="300" alt="pephub error message" />

**Two things I bring up:**
1. Should PEPhub support very large files like this?
2. If not, can we catch the [`413`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413) and render a more user-friendly toast message?

**Comment by khoroshevskyi** [comment]
75K is very huge PEP. I think PEPhub server can fail if you will try to open this pep using peppy. I would say, let's not do this. At this point max pep should be less then 10K

**Comment by nleroy917** [comment]
Yeah I agree. I say we just catch the 413 and notify the user there's a max file size limit.

**Comment by nsheff** [comment]
I agree that 75k is probably outside the scope of what we were thinking.

I'm assuming this was embeddings? Maybe we need a separate service with database of embeddings?

**Comment by nleroy917** [comment]
It was actually `GEO_GSM_complete`

**Comment by khoroshevskyi** [comment]
> It was actually `GEO_GSM_complete`

This file is more than 300 MB, it's too huge + too many columns.

**Comment by khoroshevskyi** [comment]
In the future, I think it will be possible to store such a big files if we will develop new way for getting samples, but for right now it is impossible

**Comment by nsheff** [comment]
I'm working with a group that wants to hold a large table, maybe on the scale of 10,000 records.

He pasted 2000 records into the table, and the javascript could handle it, but when he clicked 'Save' it said "Unknown Error Occurred".

with 1000 rows, it worked.

Can we clarify this?

**Comment by khoroshevskyi** [comment]
This issue was solved in pephub 0.11.9
