### ISSUE TITLE
Zip endpoint is broken

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#227]
I tried to download pep using zip endpoint. Zip was downloaded, but it was broken. Try this pep: https://pephub.databio.org/bedbase/gse218274?tag=samples

p.s. this error can be caused because of new peppy..
in case, if someone needs to download pep from pephub, you can use pephubclient for now: `phc pull "bedbase/gse218274:samples"`

**Comment by khoroshevskyi** [comment]
Error was fixed locally, but it is still broken in production

**Comment by khoroshevskyi** [comment]
Update: it was fixed

**Comment by nleroy917** [comment]
> Update: it was fixed

It was fixed by making sure the container was built before pulling the trigger on the server deployment 🙂
