### ISSUE TITLE
pephub dotfile standardization

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#23]
Right now, pephub looks for a dotfile called ".pephub.yaml" in a folder to identify the config file, and expects it look like:

```
config_file: path/to/config.yaml
```

Interestingly, looper does something very similar...it wants a file called `.looper.yaml` in the folder and wants it to look like:

```
config_file_path: path/to/config.yaml
```

We should standardize.

1. To start, let's just use `config_file_path` for `.pephub.yaml`
2. Is it worth merging `.looper.yaml` and `.pephub.yaml` into a single file?

**Comment by nleroy917** [comment]
We could support both maybe?

**Comment by nleroy917** [comment]
Otherwise, we can move to `.looper.yaml`

**Comment by nsheff** [comment]
> We could support both maybe?

instead of both maybe it makes more sense to name it a generic `.pep.yaml` or something..

**Comment by nleroy917** [comment]
Sure. We can change to that -- seems to be more intuitive inside pephub rather than `.looper.yaml`

**Comment by nsheff** [comment]
> seems to be more intuitive inside pephub rather than .looper.yaml

?

**Comment by nleroy917** [comment]
I meant `.pep.yaml` semantically works with `pephub`, sorry if that was confusing.

**Comment by nsheff** [comment]
Ok agreed, let's do this!

**Comment by nsheff** [comment]
With the switch to the back-end database, did the `.pep.yaml` file go away completely? Its original role was to point to the PEP of PEPs to include, right? So, it's deprecated now, right?

**Comment by nleroy917** [comment]
Sort of. It was designed for the file structure representation of a "database" of PEPs. Initially, the name of the pep was going to be: `folder1/folder2`, and the PEP was defined by the files inside `folder2`, but if someone didn't want to name their config file `project_config.yaml`, they could include a `.pep.yaml` file to point to the **actual** config file (say `my_pep.yaml`). We planned to use this `.pep.yaml` dot file to store any other metadata about the pep in the future, but I think it's antiquated/no longer relevant.

**Comment by nsheff** [comment]
Without a file structure representation of the PEP database, the `pep.yaml` file becomes irrelevant, right?

**Comment by nleroy917** [comment]
Yes, I believe so. Since all the data that was originally going to be stored now is stored along-side the PEP in postgres.

**Comment by nleroy917** [comment]
I can see it being relevant if you need to **convert** a file structure of PEPs into a database representation. [I have a script](https://github.com/pepkit/pephub/blob/master/scripts/load_db.py) on pephub that does this. So, the `.pep.yaml` could be useful for that. But once its in the database, it's irrelevant.
