### ISSUE TITLE
PEPhub week

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#236]
This is sort of a meta-issue, but I think that this is a good place to store issues that we should address during our pephub week:

- #230 
- #74 
- #129 
- #234 
- #240 
- #245

**Comment by nleroy917** [comment]
_moved up_

**Comment by nleroy917** [comment]
### Notes from meeting 12/08/2023
- There are a few main areas: **Search**, **error handling and validation**, and **features**.

**Comment by nleroy917** [comment]
Search is last thing that needs updated

**Comment by khoroshevskyi** [comment]
Close, all the issues were fixed
