### ISSUE TITLE
Unknown error occurred when updating PEP

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pephub#237]
If one of the columns for a pep is longer than all the others, e.g.:
![image](https://github.com/pepkit/pephub/assets/125581724/d0d6a26c-ed39-4981-9d0d-87aa18c495a2)

Pephub will error with `Unknown Error Occurred` when attempting to update or save the PEP.

**Comment by nsheff** [comment]
Can you clarify what you mean by "If one column is longer than the others" ? which column in your example are you referring to, and are you sure that's the issue? I'm not sure what column length would have to do with it...

**Comment by donaldcampbelljr** [comment]
In the above example, row 44 is clear, except for column C, genome, where there is a value. Upon deleting hg38 at row 44, column C, the error disappeared.

**Comment by donaldcampbelljr** [comment]
Ah, if I add something to the 'sample_name` column at row 44, it no longer gives the error and instead tells me the pep is invalid compared to the schema (as expected).

**Comment by nsheff** [comment]
yeah, I doubt this has anything to do with column length.

This is related to the sample identifier issues we've been happen. Basically, we need to thoroughly test the "sample_name" and related columns for things like this:

- what if `sample_name` column is missing
- what if a single sample is missing its `sample_name`
- what if there's sample_name, but the index is set to something else in the config file?

etc.

**Comment by khoroshevskyi** [comment]
custom_id works find. Example: https://pephub.databio.org/khoroshevskyi/custom_id?tag=default

**Comment by nleroy917** [comment]
- [x] what if `sample_name` column is missing
- [x] what if a single sample is missing its `sample_name`
- [x] what if there's sample_name, but the index is set to something else in the config file?

**Comment by nleroy917** [comment]
> what if a single sample is missing its `sample_name`

For some reason it lets you do this still, but I can check serverside for that too

Update: I'm just checking serverside for empty `sample_name`s (`None` or `''`)

**Comment by nleroy917** [comment]
Messing around with three scenarios and others seems to work really well. If its a 500 server error you'll get an `Unknown error occured` message. Otherwise, if we are disciplined with making sure we use `HTTPException` + `detail` on the backend and `extractErrorMessage` on the frontend things should work well.

**Comment by khoroshevskyi** [comment]
This issue was solved
