### ISSUE TITLE
searching via accession fails

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#239]
When I search for a geo accession number, it doesn't find the exact match, even if it's in the database.

**Comment by nleroy917** [comment]
@khoroshevskyi can comment but I think this is because the search is done on the project description, not the project name

**Comment by khoroshevskyi** [comment]
I assume @nsheff is talking about general (vector) search. Namespace search should find that project:)

**Comment by nsheff** [comment]
I'm just talking about the general search box:  
![image](https://github.com/pepkit/pephub/assets/5271009/7efc2af3-0095-4db6-b089-a116de3fb5f7)

**Comment by nleroy917** [comment]
That makes more sense - yeah I think I've thought this for awhile. That search box should do two searches:
1. Vector search
2. Postgres search

And we should bubble up results that contain direct matches to words in the search query.

**Comment by nleroy917** [comment]
@khoroshevskyi What function in `pepdbagent` can I use to **guarantee** that I will get back a specific PEP that I am looking for given a query?

**Comment by khoroshevskyi** [comment]
agent.annotation.get(query:"...")

**Comment by nleroy917** [comment]
Inside the search endpoint we do a direct search, I bubble up those to the top of the results on the results page

**Comment by khoroshevskyi** [comment]
solved in 0.11.0
