### ISSUE TITLE
PEP Searching

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#24]
@nsheff  Should we enable searching for peps? @Khoroshevskyi said it would be nice to search through peps. We could add a `/search` endpoint?

**Comment by nsheff** [comment]
What exactly would /search do?

**Comment by nleroy917** [comment]
@Khoroshevskyi ?

**Comment by khoroshevskyi** [comment]
I was just trying to understand how people will use pephub. Will they search for exact projects that they are interested in? How and Where can you find information about pephub project (PEPs) in it?(e.g. We have experiment in GEO, and we want PEP for it. Will we search for it in PEPHub, or will this information be somehow provided in GEO . How projects will be linked to origin location of the projects)

Or maybe we want to know if this project has this file type.(e.g. bed files)
___ ​

Thats why I had question and thoughts about searching endpoint.

**Comment by nsheff** [comment]
did you decide against this?
