### ISSUE TITLE
Store project search state in the url

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#240]
If you go to either an organization's or a user's repository list on GitHub, you can search through their repos. this is similar to how PEPhub lets you search through a namespace. In GitHub's implementation, if you search for something using the search bar, click on a result, and then go back (go to previous page) the search state remains. This is because GitHub stores the search state in the URL query params:

<img width="447" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/39ac0eb4-ba91-41dc-a920-1f4200ebf642">

We should implement something similar so users can navigate back and forth between searches and projects

**Comment by nleroy917** [comment]
This is complete for navigating between `/{namespace}` and `/{namespace}/{project}`

**Comment by khoroshevskyi** [comment]
This issue was solved in v0.11.0
