### ISSUE TITLE
Pagination: show number of pages

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#241]
For pages where the number of items are known, the number of pages could be shown (and actually, links to some of those pages could be included?)

**Comment by nleroy917** [comment]
How's something like this?
<img width="422" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/7d41cfb3-aa1f-4af9-8269-9f0c4ea216f3">

**Comment by khoroshevskyi** [comment]
I like it

**Comment by nleroy917** [comment]
For something like GEO, it looks like this as you page through a bunch:

<img width="500" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/9fbf7836-14e4-46c4-a465-7e0f17b8bb11">

**Comment by nleroy917** [comment]
And this

<img width="499" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/421599d4-332d-4dbc-a49a-41d2736df748">

**Comment by nsheff** [comment]
yes, that's great.

But I'm not sure we should have the "End" button; since we're using offset pagination, the performance there will be really bad

**Comment by khoroshevskyi** [comment]
solved in pephub 0.11.0
