### ISSUE TITLE
load_db.py error 

### ISSUE THREAD

**Issue by mathob** [pepkit/pephub#252]
I get this error when attempting to load example data as described in the README:

python load_db.py --username docker --password password --database pephub ../examples
Traceback (most recent call last):
  File "/Users/mathob/git/pephub/scripts/load_db.py", line 4, in <module>
    from pepdbagent import Connection
ImportError: cannot import name 'Connection' from 'pepdbagent' (/Users/mathob/git/pephub/venv/lib/python3.10/site-packages/pepdbagent/__init__.py)

pepdbagent version is 0.6.0

**Comment by nleroy917** [comment]
Hi @mathob 

Thanks for pointing out this error! That script is a bit out of date, unfortunately. I've made a change that uses the latest `pepdbagent` API and pushed directly to master. If you want to try that new script let me know how it works out for you.

**Comment by mathob** [comment]
Thanks for that quick response.

Modified script runs OK for a while and a number of examples are loaded, which I can see in my pephub; however it runs into this error before completing:

                                                                                                                                 [INFO] [11:48:30] Uploading geo/gse104545:default project...████████████████████████████████▉    | 143/151 [00:05<00:00, 25.54it/s]
[INFO] [11:48:30] Uploading geo/gse94278:default project...
[INFO] [11:48:30] Uploading geo/gse140251:default project...
[INFO] [11:48:30] Uploading geo/gse128744:default project...
                                                                                                                                 [INFO] [11:48:30] Uploading geo/gse138571:default project...██████████████████████████████████▉  | 147/151 [00:05<00:00, 25.69it/s]
[INFO] [11:48:30] Uploading geo/gse143684:default project...
[INFO] [11:48:30] Uploading geo/gse131257:default project...
[INFO] [11:48:31] Uploading geo/gse97008:default project...
Uploading repository:  40%|█████████████████████████████▏                                           | 2/5 [00:06<00:09,  3.02s/it]
Traceback (most recent call last):                                                                          | 0/3 [00:00<?, ?it/s]
  File "/Users/mathob/git/pephub/scripts/load_db.py", line 100, in <module>
    p, name, p.name, description=f"Uploaded from, {path_to_proj}"
  File "/Users/mathob/.local/lib/python3.10/site-packages/peppy/project.py", line 1376, in name
    return self.infer_name()
  File "/Users/mathob/.local/lib/python3.10/site-packages/peppy/project.py", line 986, in infer_name
    raise NotImplementedError(
NotImplementedError: Project name inference isn't supported on a project that lacks a config file.

**Comment by mathob** [comment]
btw your site https://pephub.databio.org/ is down...

**Comment by nleroy917** [comment]
We are having AWS issues 🥴 We are actually close to another release! Fingers crossed by end of week.

RE: your issue
> NotImplementedError: Project name inference isn't supported on a project that lacks a config file.

I'll ping @khoroshevskyi - he knows more about core `peppy` than me

**Comment by mathob** [comment]
Thanks. Since I now have some examples loaded this issue is no longer a problem for me.

**Comment by nleroy917** [comment]
Glad it got you somewhat there. I'll open a separate issue to track that error.
