### ISSUE TITLE
Why are links using external window targets?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#26]
It's strange to me that the links on the pephub landing page are all opening targets in new windows. is there a reason you did it that way?

To me it's frustrating, as I generally don't expect links to do that. I don't see a reason for doing it here.

**Comment by nleroy917** [comment]
Hmm, I think since it was a "demo" of the API you could open it in a new window to see the results and still have the docs open.

I think it does make more sense to **not** open a new link. Let's change it back.
