### ISSUE TITLE
Remove project representation from samples endpoints

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#27]
Right now if you hit a `/samples` endpoint, you get the samples, but each sample includes a pointer back to the project under `_project`. 

We shouldn't duplicate the project information like that.

**Comment by nleroy917** [comment]
Does it make sense to remove all "private" attributes? I.e. those that are prefixed with an underscore (`_`)

**Comment by nsheff** [comment]
Hmm. Yes, based on what I am seeing, I think you're right. 

http://pephub.databio.org/pep/demo/BiocProject/samples/vistaEnhancers

![image](https://user-images.githubusercontent.com/5271009/166565790-467024a1-41c0-4699-bf40-fc24012c8f5c.png)
