### ISSUE TITLE
Bugs in v011.2

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#270]
- [x] If you are not logged in, ui shows that there are 0 projects in the namesapce  (see screenshot below)
- [x] POP doesn't show **JUST** pops in peps that were stared 
- [x] Adding to project to POP is not working (see screenshot below)
- [x] Subsamples endpoint is failing 
- [x] Zipping and downloading of PEPs is not working 
- [x] Add information about a number of stars on the project page
![image](https://github.com/pepkit/pephub/assets/41573628/77b9c774-c86d-4933-a270-6e59979a6083)
![image](https://github.com/pepkit/pephub/assets/41573628/858d5446-9885-4890-8cec-284c3aa80771)

**Comment by nleroy917** [comment]
> If window is small, burger button on the top is not showing the list of options (see screenshot below)

Not sure why this isn't working, but regardless that mobile nav will look super weird, so maybe we need to rethink that one. I am using the bootstrap nav out of the box, but we might need to customize a bit more

**Comment by khoroshevskyi** [comment]
All Issues were fixed, closing this issue
