### ISSUE TITLE
Should schemas be part of PEPhub?

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#271]
Now, the process of creating and uploading schemas is a bit complicated. Additionally, schemas currently live on GitHub as files. Would it be beneficial for schemas to be integrated into PEPhub, allowing users to create and update their own schemas? 

It would be easy for users to create and validate correctness of schemas quickly.

**Comment by nleroy917** [comment]
I think that this was discussed in Infrastructure meeting yesterday (01/23/2024) that schemas will exist inside their own database, correct?

**Comment by khoroshevskyi** [comment]
I think after discussion, we decided that in the long term it should be part of PEPhub.

**Comment by nleroy917** [comment]
Where should schemas be viewed/edited? `https://pephub.databio.org/schemas` or maybe `https://pepub.databio.org/{namespace}/schemas` ?

**Comment by nleroy917** [comment]
This is about to be resolved...

**Comment by khoroshevskyi** [comment]
Fixed in 0.13.0
