### ISSUE TITLE
Add Views to Project page

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#274]

**Comment by nleroy917** [comment]
@khoroshevskyi Could you add some description of exactly what the reqs are here? Like maybe a [user story](https://www.atlassian.com/agile/project-management/user-stories)

**Comment by khoroshevskyi** [comment]
1) On a project page should be a drop-down button, that shows available view (I think we don't have API for that, so it can be skipped for now)
2)  Projects with more than 5K should not be retrieved , and message should be generated: "use vies to view the project" .. or something like that
3) The views page should be the same as  project project, but in views page in metadata section will be only a description and the sample table should be `view` only (no modifications are allowed).

**Comment by nleroy917** [comment]
This got implemented in `v0.11.8`
