### ISSUE TITLE
POP as a new tab

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#275]
I know that it's programmatically hard, but is it possible to make POP as a new tab?
I was speaking with few people, and all of them want POP to be a new tab (next to stars), beacuse it is very confusing to have pop as toggle

![image](https://github.com/pepkit/pephub/assets/41573628/e958f189-c5c0-4a76-ab3c-1eec9ae1b2a6)

**Comment by khoroshevskyi** [comment]
I like how Google is doing that in Google Drive
"It is much more cleaner" - Edward said
![image](https://github.com/pepkit/pephub/assets/41573628/b5aa04af-4ec5-412d-af63-006bc001b916)

**Comment by nleroy917** [comment]
Im not google :(

**Comment by nleroy917** [comment]
but yeah, I can work on this

**Comment by nleroy917** [comment]
This will be addressed in the latest release
