### ISSUE TITLE
Users can modify POPs from other users

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#282]
Users with no write permission can modify views of other users.

**Comment by nleroy917** [comment]
I'm confused. The title says:
> Users can modify **POPs** from other users

But the body text here says:
> Users with no write permission can modify **views** of other users

POPs are just PEPs, so I would be a bit surprised if they were somehow excused from our normal authorization flow on the server... do you mean the `views` endpoints are not secure?

**Comment by khoroshevskyi** [comment]
https://pephub.databio.org/khoroshevskyi/alex_pop?tag=default
Try to use this pop to add files 
You should not be able to do that

**Comment by nleroy917** [comment]
Still not sure how I would modify this on the UI... are you saying in API requests it can be modified?

**Comment by nleroy917** [comment]
This seems slightly resolved, the UI just needs to reflect it

**Comment by nleroy917** [comment]
This should now be resolved
