### ISSUE TITLE
marking a pep as a pop fails

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#283]
I have a pep. I click 'edit' , then I slide the toggle for "POP".

it acknowledges "metadata updated"

Nothing changes in the interface.

I click edit again -- it's still not a POP.

I can't change a PEP to a POP.

**Comment by nleroy917** [comment]
I need @khoroshevskyi to help here. It should be easy - but I don't know how to actually use `pepdbagent` to change a PEP to a POP

**Comment by nleroy917** [comment]
This is where the project updates happen
```python
agent.project.update(
        dict(project=Project().from_dict(new_raw_project), **update_dict),
        namespace,
        project,
        tag,
    )
    ```
    but... I don't really know where `POP` gets specified.

**Comment by nleroy917** [comment]
`new_raw_poject` looks like this:
```python
{'_config': {'pep_version': '2.1.0', 'sample_table': 'samples.csv', 'name': 'my-pop', 'description': '', 'pop': True}, '_sample_dict': [{...}, {...}], '_subsample_list': []}
```
and `update_dict` looks like this:
```python
{'pop': True}
```
So I am not sure where its getting lost. I could have an out of date package or something, though

**Comment by nleroy917** [comment]
Anyways, if we can get that to propagate, then all should be well

**Comment by khoroshevskyi** [comment]
I will fix it, there is bug in forking and updating projects
