### ISSUE TITLE
update schema urls

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#284]
with updates to schema.databio.org, the URLs to schemas and schema downloads need to change.

but let's first finalize what we want those URLs to look like. what URL do we want?

example:

old: `https://schema.databio.org/#/schemas/#/pipelines/#/bedbuncher`
new: `https://schema.databio.org/?namespace=pipelines&schema=bedbuncher`

The new ones are already a lot better than the old ones, but are they what we want? other ideas:

- use registry path: `https://schema.databio.org/?schema=pipelines/bedbuncher`
- use an API subfolder? eg `https://schema.databio.org/view?namespace=pipelines&schema=bedbuncher`

**Comment by nleroy917** [comment]
> use an API subfolder?

I like this idea. Would prefer `/api`, however

**Comment by nsheff** [comment]
well `/api` would indicate the computer-readable ones, right? This is referring to the HTML splash pages...

**Comment by nsheff** [comment]
RIght now its:

HTML view dashboard page: `https://schema.databio.org/view?namespace=pipelines&schema=bedbuncher`
API to actual schema: `https://schema.databio.org/pipelines/bedbuncher.yaml`

**Comment by nleroy917** [comment]
~~I think that it was decided that:~~
- ~~HTML view dashboard page remains at: `https://schema.databio.org/?namespace=pipelines&schema=bedbuncher`~~
- ~~API to actual schema will be at `https://schema.databio.org/api/pipelines/bedbuncher.yaml` and `https://schema.databio.org/api/pipelines/bedbuncher.json`~~

See below:

**Comment by nsheff** [comment]
- https://schema.databio.org/view?namespace=pipelines&schema=bedbuncher
- https://schema.databio.org/pipelines/bedbuncher.json

**Comment by nleroy917** [comment]
Outdated as schemas are now integrated with PEPhub
