### ISSUE TITLE
validator is failing

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#285]
not sure if it's due to updates in schema.databio.org but anyway:

![image](https://github.com/pepkit/pephub/assets/5271009/3fbaa125-bbb4-4564-ad72-89626bd63c4e)

**Comment by khoroshevskyi** [comment]
Additionally, if project is invalid, validator is not showing where are the problems in the PEP

**Comment by nleroy917** [comment]
> not sure if it's due to updates in schema.databio.org but anyway:

I think that it is, its a server-side error indicating that 
```json
{ 
    "error": "Error fetching schema: 404 Client Error: Not Found for url: https://schema.databio.org/schemas/pipelines/bedboss.yaml" 
}
 ```
 If you remove `/schemas/` it wants to download it. But why are the schemas on the UI all prefixed with `schemas/` ? Is that correct? I think we need to remove that

**Comment by nleroy917** [comment]
I see. Its because `https://schema.databio.org/list.json` leads to a list where they are all prefixed wth `schemas` - I think I'll just strip that out?

**Comment by nsheff** [comment]
Did they used to be at `/schemas` and then I moved them and didn't update the API? maybe oops...

**Comment by nleroy917** [comment]
Not too sure... I got it working though. I just am doing this on the UI for that little dropdown selector:
```typescript
  const options = Object.keys(schemas || {}).map((schema) => ({
    label: schema.replace('schemas/', ''),
    value: schema.replace('schemas/', ''),
  }));
  ```
  
  Which works, but I think it would be nice to either change that `json` list or perhaps add another attribute that gives the registry path of the schema, maybe? Something like:
  ```json
{
    "schemas/refget/annotated_collection_digest": {
        "registry": "refget/annotated_collection_digest",
        "project": "refget",
        "url": "refget/annotated_collection_digest.yaml",
        "description": "Schema for an Annotated Collection Digest; this is analogous to a single fasta file with metadata."
    },
    "schemas/refget/SeqColArraySetInherent": {
        "registry": "refget/SeqColArraySetInherent",
        "project": "refget",
        "url": "refget/SeqColArraySetInherent.yaml",
        "description": "SeqColArraySet"
    },
    ...
}
  ```

**Comment by nleroy917** [comment]
> Additionally, if project is invalid, validator is not showing where are the problems in the PEP

Is this just because it was broken? I see issues now:
<img width="740" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/4918a489-1758-41ee-953c-5e1a1a7d22a6">

**Comment by khoroshevskyi** [comment]
This issue was solved
