### ISSUE TITLE
Edit table should adjust to the current screen

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#287]
I don't see the bottom scroll bar while editing pep on pephub. And it bothers a lot of users

**Comment by nleroy917** [comment]
Example of one that is particularly egregious that I can fork and test out on my own?

**Comment by nleroy917** [comment]
Actually, this is hard for me to reproduce. I always get a bottom scroll bar

**Comment by khoroshevskyi** [comment]
http://localhost:5173/khoroshevskyi/alex_pop?tag=default
Try to use this pop to add files 
You should not be able to do that

**Comment by khoroshevskyi** [comment]
you can make huge description, this is the way you reproduce it

**Comment by khoroshevskyi** [comment]
Example
https://pephub.databio.org/khoroshevskyi/bedboss_test_gse201797?tag=samples

**Comment by nleroy917** [comment]
i see - this makes sense. I'll use this as a guide to try and fix this

**Comment by nleroy917** [comment]
So, my idea is to just use JavaScript to grab the difference in height between the top of the sample table and the top of your browser window, and use that to compute the height of the table. It's like one line of code and should work well.

I suppose, however, the downside to this is that if you have huge descriptions, your sample table will be very very small. In fact if the description is so large that it rolls down the page then you'll end up with a sample table with negative height?

I suppose a more intelligent solution is one where you can "scroll away" that top section, but that might require more thought about how to do that one.

**Comment by khoroshevskyi** [comment]
Is it possible to set max window length for the description, like a scroll bar?

**Comment by nleroy917** [comment]
yeah I can - thats kind of what i was thinking, it just might look weird? I can try it out

**Comment by nleroy917** [comment]
Yes this is easy - it just looks weird when scrolling....

<img width="1331" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/113f91c4-ddeb-4159-8344-29852e4c586f">
