### ISSUE TITLE
Disable editing large PEPs (>5K samples)

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#289]
We should disable editing huge pages in the endpoint and UI. If we want to update PEPs larger than 5K, we will have to use the sample endpoints.

**Comment by khoroshevskyi** [comment]
- [x] Additionally, this peps should be visible in namespace. This functionality was disabled earlier

**Comment by nleroy917** [comment]
So they can **view** the samples? Just not edit?

**Comment by khoroshevskyi** [comment]
unfortunately, this issue seems not solved

**Comment by khoroshevskyi** [comment]
This issue should be fixed in 0.11.8
