### ISSUE TITLE
Horizontal scroll bar glitches with many columns when using the mouse

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pephub#293]
This specific PEP is a good example:
https://pephub.databio.org/bedbase/gse249578?tag=samples

I have to click on the cells and use the arrow keys to go to the right most columns.

**Comment by donaldcampbelljr** [comment]
Potential fix reading:
https://forum.handsontable.com/t/set-max-column-width/6619

**Comment by khoroshevskyi** [comment]
Fixed
