### ISSUE TITLE
Add help to new PEP interface

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#304]
people are confused when creating a PEP:

![image](https://github.com/pepkit/pephub/assets/5271009/589ab8c0-0bb4-4c4d-8f4d-d523efb3052f)

what are these boxes? they have no labels.

It's not clear that the first is namespace, the second is project name, and the third is tag. Can you make that clearer?

**Comment by nleroy917** [comment]
Not really the issue for it, but how necessary are tags? I never use them...

**Comment by nleroy917** [comment]
I propose just copying GitHub's interface: 
<img width="416" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/322422e1-e053-4e72-8d83-c7d3fc510637">

**Comment by nleroy917** [comment]
Added this to the forms:
<img width="772" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/06c5e4df-1d5e-446c-9e2a-1d1fc8a212ca">
