### ISSUE TITLE
Multiple users editing the same PEP can cause issues

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#309]
Currently, there are no ways to mitigate the issue of two people editing one PEP at a time... the canonical example here is google docs. Multiple users can edit one Google doc simultaneously, and you can see, in real time, what's going on...

Currently, PEPhub just assumes you're the only one editing that PEP, and so it will just overwrite anything that's been written. We need a way to understand which users is on which PEP right now.

It probably (or almost certainly) will require the use of web sockets ([socket.io](https://github.com/socketio/socket.io))

**Comment by nsheff** [comment]
either websockets if you want to go with Operational Transform (OT), or you can use a check-in/check-out system, in which case websockets would not be required

**Comment by nleroy917** [comment]
Last week (or maybe the week prior) I demo'd a basic system where we can, at the very least, indicate to users that there are other people on the same page... Kind of like how Google Sheets does it (e.g. anonymous narwhal...)

The demo will let you know if someone made a change to the sample table, but the trick is getting everything updated fast. It takes 2-3 seconds for the "save" to run. And if a lot of people are all making changes it could become unwieldy.

**Comment by nleroy917** [comment]
The system needs re-wired at the **sample** level, instead of the **project** level for more instantaneous updates.

Bigger, problem is parallel, programmatic writing

**Comment by nleroy917** [comment]
Currently, this is deemed way to big a problem to tackle for now. Closing unless we really want to revisit this in the future.
