### ISSUE TITLE
Is this the best list output ?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#31]
Right now the namespace output is an object, with keys corresponding to projects in that namspace, and values are, I guess, the filepath on the local server to the project config file?

![image](https://user-images.githubusercontent.com/5271009/168898881-e2ea23e8-c7ad-4416-a480-4dae754d1f6a.png)

I see how the keys are useful, because they are the identifiers that can be used to get further information about the project. But what's the point of those values?

I think this endpoint should be serving an overview about the projects. What more useful information could be served here? Maybe number of samples in the project? 

Or maybe it's just a list of the keys. The local paths just confuse things.

**Comment by nleroy917** [comment]
I agree it can be better. What about a link to the actual project endpoint, and then like you said some summary info about it?

Maybe a response like,

```json
{
  "projects": [
    {
      "name": "GSE110633",
      "n_samples": 60,
      "href": "https://pephub.databio.org/pep/geo/GSE110633"
    },
    {
      "name": "GSE131956",
      "n_samples": 74,
      "href": "https://pephub.databio.org/pep/geo/GSE131956"
    },
    ...
  ],
  "n_projects": 100
}
```

**Comment by nleroy917** [comment]
Thinking about this more... providing some data about each project in a particular namespace would require us to load each one into memory using `peppy` first every time this endpoint is hit. For namespaces with a large number of projects, this could get pretty non-performant.

Maybe it makes more sense to index it when the server is instantiated in that `_PEP_STORES` object we use.

**Comment by nleroy917** [comment]
@nsheff I've got the server indexing/pre-processing the PEPs on startup and that way it can give data like above without loading them all for each call to that endpoint. This output now looks more like this:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/41063083/169140928-5c0ef319-2294-4025-957b-b5c6133166a6.png">

I'm still working out the `href` attribute.

**Comment by nsheff** [comment]
That is great!

I'm not sure the `cfg` attribute as listed here is adding much, though.

**Comment by nleroy917** [comment]
`cfg` is an artifact of the parsing on server load. I guess we could loop through and remove it.

**Comment by nsheff** [comment]
I'm not sure about the implementation -- I'd rather just create the object without it in the first place, rather than loop through to remove it -- but I'm just referring to the user experience. It doesn't add any useful information for the user, so there's no value in including it in the API response, only cost of bandwidth and confusion with interpreting.

**Comment by nsheff** [comment]
http://pephub.databio.org/pep-list

**Comment by nleroy917** [comment]
I've got it producing a much richer output... Not sure if this is a high priority, however.

**Comment by nsheff** [comment]
just make sure you remove the `cfg` entry, which doesn't make sense
