### ISSUE TITLE
Expand project description in search

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#311]
When users are searching projects, in the filed `projects found` there is not enough description to understand if project is relevant to what you are searching for.

Sooo, it would be nice to add `expand description` or `expand info` about the project.

Additionally:
- [ ] Add created and last update date

![image](https://github.com/pepkit/pephub/assets/41573628/61abe84a-66da-4458-bf0e-9768a8c50b4a)

**Comment by nleroy917** [comment]
> Sooo, it would be nice to add expand description or expand info about the project.

I think we need to add this to the payload, or populate it on the way back to the UI

**Comment by nleroy917** [comment]
Tried to add this... need to do better detecting when things are overflowing
