### ISSUE TITLE
UI allows you to enter invalid characters for Project Name and Tag

### ISSUE THREAD

**Issue by sanghoonio** [pepkit/pephub#315]
It looks like there is server side validation that checks for invalid characters like ':' or '|' in the project name or tag, but if you enter a '/' or '\\' it will break PEP lookup by the API.

**Comment by nleroy917** [comment]
Should we do a **whitelist** approach, or a **blacklist** approach? I kind of am partial to whitelisting, so we aren't constantly saying to ourselves, "oh shoot we should ban that character too"

A potential whitelist could be:
1. Alpha-numerics
2. underscores (`_`)
3. Hyphens (`-`)

A potential blacklist could be:
1. slashes (`\`, `/`)
2. pipes (`|`)
3. dollar signs (`$`)
4. Quotes? (`'`, `"`)

**Comment by nleroy917** [comment]
Also, the UI should definitely have validation in the submission forms, but we should validate on the API as well -- since the PEPhub UI is not the only way to submit PEPs

**Comment by sanghoonio** [comment]
I like whitelisting also, thinking of using a regex pattern like this in pepr:

```R
pattern <- "^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+$"
```

**Comment by nleroy917** [comment]
Regex 🤢

Jk.. thats probably fine, as long as we don't get too complex haha

**Comment by nleroy917** [comment]
Gonna keep open until verified in deployed production version
