### ISSUE TITLE
Namespace splash page

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#32]
Piggybacking off #31 

It might be nice to have an HTML, user-friendly page that shows the same info you're putting into this endpoint. So, it would be a list of the projects for a namespace, with some metadata (number of samples), and a link to the project, some API endpoint links, etc. For browsability.

**Comment by nleroy917** [comment]
I like that idea. Would that break the programmatic approach? Software would have to parse HTML at the namespace endpoint.

**Comment by nsheff** [comment]
No, this can in theory be a client-side rendering of the same information that comes from the API endpoint. You're right that parsing HTML from an endpoint wouldn't make sense.

**Comment by nleroy917** [comment]
Hm. You might have to explain this some more. Do you mean something like `/pep/namespace/splash`? Or is it `/pep/namespace/` that will return `JSON` when called programmatically and then render HTML in the browser?

I am unaware of how to achieve the second option. That's not something I have done before.

**Comment by nleroy917** [comment]
**Infrastructure Meeting 05/23/2022:**
- The splash page should be a separate endpoint (`/pep/namespace/splash`)
- Use `jinja` to SSR the HTML
- Splash pages for namespace, project, and sample.
- Look at regenie for endpoint naming conventions
- Maybe `/view`

**Comment by nleroy917** [comment]
I have splash pages sitting at the following endpoints on the `dev` branch:
## `/peps/view`: View all peps summary as splash page:
![image](https://user-images.githubusercontent.com/41063083/170067975-b7d26371-9c8f-4e7a-828e-990bd578a987.png)

## `/peps/<namespace>/view` View a particular namespace as splash page
![image](https://user-images.githubusercontent.com/41063083/170068118-317b2a63-48a6-444c-9330-20dfdfc2bc2f.png)

I think it could be better. Open to styling/layout ideas. It gets pretty hard to navigate when there are a lot of namespaces or projects.

**Comment by nsheff** [comment]
Some ideas:

- [x] Maybe use [cards](https://getbootstrap.com/docs/5.0/components/card/) since you don't need to use all that horizontal space.
- [ ] What do you think of having a 'description' field with some text for each namespace, describing what the namespace represents? It would be optional.
- [ ] Is there any other information you should include at either level? so, anything else you can say about a namespace, on the namespace list page, or anything else you can say about a project, on the project list page?
- [x] maybe "Available projects" for the title, for parallelism?
- [ ] alphabetically sort the projects and namespaces? (should probably return them sorted alphabetically from the API endpoint)

**Comment by nleroy917** [comment]
I initially tried using cards, but it looked like the CSS wasn't working. I think the contrast settings on my monitor were messed up so I couldn't see borders/bg styling. I can switch it up.

> What do you think of having a 'description' field with some text for each namespace, describing what the namespace represents? It would be optional.

I definitely like that idea a lot. Where would the description "field" be held? Maybe in another `.pep.yaml` file at the namespace level?
```
|_ namespace/
|____ project1/
|________project_config.yaml
|________sample_table.csv
|________.pep.yaml
|____.pep.yaml
```
Just like the project-level `.pep.yaml` file, it is optional and can have a description field, etc. ~We can probably look for a description field too on the projects~. Actually, peps already have the option to provide a description field, so maybe we can render that if it exists

**Comment by nsheff** [comment]
Have you thought about structuring the list of namespaces as a PEP of PEPs? That is, there's a table with each row describing a namespace, basically.

**Comment by nsheff** [comment]
Currently, the way the demo links are shown does not make any sense to me. The main page is showing links to particular API endpoints for demos, and these links are not available on the actual demo namespace page.

Instead, the links to "View info about a namespace", and "view a project configuration file" Should show up on the page for the particular namespace, which would be this page:

http://pephub.databio.org/pep/demo/view

**Comment by nsheff** [comment]
have you deployed changes to the layout? it still is really bad use of space: http://pephub.databio.org/pep/geo/view

![image](https://user-images.githubusercontent.com/5271009/173365307-2549f503-b9cf-4924-acc0-3c5d6f7afc35.png)

I think probably even cards will not be ideal here, These should really be rows in tables.

The same thing needs to happen for the list of namespaces.

**Comment by nleroy917** [comment]
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/41063083/173419825-f790fff5-d215-4f6c-9328-d8bd39e5b97f.png">

Here is the namespace splash page.. there is only one endpoint for this. What else should be included at the namespace level?
