### ISSUE TITLE
Add pephubclient link (or phc docs) to the main page

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#331]
Add pephubclient link (or phc docs) to the main page so people will know that pephubclient exist

**Comment by nleroy917** [comment]
I think we should do something similar to bedbase too:

<img width="1324" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/23f43b7e-712b-422b-99d3-c24e53b5346e">

**Comment by khoroshevskyi** [comment]
Fixed in 0.13.0
