### ISSUE TITLE
bugs in upload pep UI

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#332]
1. If you go to submit a new pep and then click "upload PEP", the submit button only becomes active if you drop a file. If you click "browse", it says deactivated.
2. If you drop 2 files, and then click the "x" to get rid of one, the dialog closes.
3. If you press "cancel", nothing happens.

**Comment by nsheff** [comment]
Sorry more issues:

1. I was wrong above. it's actually that it requires you to have a name before it becomes activated. This is highly unintuitive for me and I just spent several minutes trying to figure it out. I suggest instead: Don't disable/enable the submit button on a opaque reason, instead, just allow me to click "submit" and then say "You must provide a project name" if that is missing. that will be much more clear.
2. even if I figure all this out and click submit, the UI is not working; it says this for everything I try to do, even things that clearly don't exist in the namespace:
![image](https://github.com/pepkit/pephub/assets/5271009/70cea11d-3939-46f0-b5f3-91ea3f6bf01a)

**Comment by khoroshevskyi** [comment]
It is due to new changes to the database. We have to release new pephub ASAP
@nleroy917

**Comment by nleroy917** [comment]
> If you drop 2 files, and then click the "x" to get rid of one, the dialog closes.

I cannot replicate this one

**Comment by nleroy917** [comment]
Unless someone else like @khoroshevskyi or @sanghoonio can replicate that... I guess I'll add the "likely solved" tag
