### ISSUE TITLE
pephub UI cannot delete a sample the inutitive way

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#337]
If you add a sample, click save,
then delete that sample, and click save -- it will fail with this error:
![Screenshot from 2024-07-05 10-26-25](https://github.com/pepkit/pephub/assets/5271009/f4cb929d-771e-4745-8bdf-abf952848419)

This obviously doesn't make sense

**Comment by nsheff** [comment]
This is fascinating. Then if you click to a different browser tab, and then then come back to the tab, the sample you tried to delete returns.

**Comment by nsheff** [comment]
So, it looks like the way to delete a sample is that you have to right-click the row and click "remove row".

**Comment by nleroy917** [comment]
Ok so, the core issue here is that `ph_id` still exists (because it was hidden) and we need to filter our samples who have `null` for all attributes

**Comment by nleroy917** [comment]
Resolved
