### ISSUE TITLE
pephub UI removes samples in progress if you switch to a different tab without saving

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#338]
Steps to reproduce:

1. Open a project. 
2. Add a new sample row to the project, but DO NOT SAVE.
3. Switch to a different tab in the browser
4. Switch back to the PEPhub tab you were editing

All your unsaved work will disappear!

**Comment by nleroy917** [comment]
I think I have solved this. The core issue, is that the `<SampleTable />` component was *re-rendering* when you clicked back over to the tab. Using the [react profiler](https://stackoverflow.com/a/41005065/13175187) I was able to trace the exact reason why it rerendered. It ended up being that the `onChange` prop **changed** when the user refocused the window.

The `onChange` prop was tied to the `setNewProjectSamples` function. I am really not too sure why that function was changing. It was probably something way upstream triggering some other rerenders while we check for the user's session validity (look into `localStorage`, etc).

Anyways. React has a convenient `useCallback` hook:
> useCallback is a React Hook that lets you cache a function definition between re-renders.

So we can cache that `setNewProjectSamples` function in between renders and now the sample table won't re-render.
