### ISSUE TITLE
Feature request: Ctrl+S to save

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#339]
Would be nice to wire up Ctrl+S to save changes.

**Comment by nleroy917** [comment]
This should be in there, not sure why it doesn't work -- but I will look into it

**Comment by nleroy917** [comment]
I think the `shouldFetchSampleTable` boolean might have been messing with things. Removed and it seems to work. Also, we might not need the `shouldFetchSampleTable` flag anymore with Alex's updates
