### ISSUE TITLE
Confusing message: "schema is invalid"

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#341]
for a project, I keep seeing this error:

![image](https://github.com/pepkit/pephub/assets/5271009/bc45ec65-6cbe-4fc0-bdf1-2ff80d39a2c9)

I don't know what it means; this project has selected the generic pep 2.1.0 schema.

Is it the schema that is invalid? But it works for many other projects. So I know the schema isn't invalid...

What is actually wrong here?

**Comment by nleroy917** [comment]
@khoroshevskyi You mentioned this was due to changes to the validation API? Anything we need to do here?

**Comment by khoroshevskyi** [comment]
Fixed
