### ISSUE TITLE
UI is creating bogus column names when you remove existing columns.

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#344]
When I delete a column name, it is automatically replaced with `column_x`.

**Comment by nleroy917** [comment]
Explained why in #343.

This will be resolved with changes

**Comment by nleroy917** [comment]
Here is an example. With changes discussed in #343, you can save with `null` column headers, but again this might lead to unexpected behavior:

![Jul-17-2024 09-50-43](https://github.com/user-attachments/assets/6fd2117a-0f73-4f0b-9a77-a782201301ff)

Where the server is putting `"null"` as a string in there. Not sure if this is good or bad... I guess again its a question on if we want to just want the user and save, or refuse to save until they fix the issue. I suppose I am partial to the latter.

**Comment by nleroy917** [comment]
I am opting to just not let the user save unless they either 1) delete the column, or 2) give it a name
