### ISSUE TITLE
Moving to 'config' tab loses all unsaved changes in 'samples' tab

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#346]
Steps to reproduce:

1. make some changes in sample table.
2. don't save yet; switch to config to make some changes there.
3. go back to 'samples' -- all your changes will be gone.
4. go back to 'config' -- all your changes will be gone again.

**Comment by nsheff** [comment]
Now it's trying to be smart and prevent me from saving the file with a broken sample_table_index: 

![image](https://github.com/pepkit/pephub/assets/5271009/b2284112-e53d-41bf-a7c6-a172da082d05)

But the thing is, I can't change it, because I can't go to that tab and take away `sample_name`, because then it gives me the same error in the other direction!

**Comment by nsheff** [comment]
Maybe related to #338 ?

**Comment by khoroshevskyi** [comment]
Also faced with this issue, I would say it should be fixed ASAP
