### ISSUE TITLE
PEPhub won't save a table without `sample_name`

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#347]
![image](https://github.com/pepkit/pephub/assets/5271009/479d4bbf-49d6-4be4-b84a-ad026f7385c6)

But what if I don't want it to have a sample_name column?

Why is the UI enforcing these rules? These should be handled by the validator, not by a draconian UI.

**Comment by nsheff** [comment]
When I do change a column to `sample_name`, then click save, then it says: 

![image](https://github.com/pepkit/pephub/assets/5271009/9c4305a1-ce81-4451-9ad5-bb37cec91fc0)

**Comment by nleroy917** [comment]
Related to #337?
