### ISSUE TITLE
Cannot add "status" column to PEP

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pephub#353]
During testing of reporting status flags to PEPHub via Pipestat ("completed", "running") I noticed that the status column does not appear on PEPHub. However, the column is there when I retrieve the values. During troubleshooting, I noticed that PEPHub will not allow me to manually create a status column. As soon as a I type it in and click away it disappears before I can press the save button.

**Comment by donaldcampbelljr** [comment]
Oh, it is this PEP in particular:
https://pephub.databio.org/donaldcampbelljr/pipestat_demo?tag=default

while this one works fine (created more recently):
https://pephub.databio.org/donaldcampbelljr/pipestat_demo_2?tag=default

**Comment by donaldcampbelljr** [comment]
Changing some other value of the table and saving the PEP allows for the status table to appear.

**Comment by nleroy917** [comment]
I can't seem to resolve this, and honestly it was probably related to sample table issues that have been resolved. Closing for now
