### ISSUE TITLE
More key bindings

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#356]
I believe that I have solved the `ctrl+s` key binding problem from #350 and #339.

What other ones can we implement? GitHub has [a ton](https://docs.github.com/en/get-started/accessibility/keyboard-shortcuts) and I use them a lot. Wondering if we can add some of our own

**Comment by nleroy917** [comment]
One I like is `ctrl+enter` when submitting forms

**Comment by khoroshevskyi** [comment]
Fixed in 0.13.0
