### ISSUE TITLE
Project splash page: Add links to API endpoints

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#36]
I think the splash page for a project should have links to show how to actually get some stuff.

for example, this page: 
http://pephub.databio.org/pep/nfcore/demo_rna_pep/view

should have a link to : 

- project: http://pephub.databio.org/pep/nfcore/demo_rna_pep/
- samples: http://pephub.databio.org/pep/nfcore/demo_rna_pep/samples
- maybe conversion formats? That woudl be:
  - http://pephub.databio.org/pep/nfcore/demo_rna_pep/convert?filter=csv
  - all other available formats (http://pephub.databio.org/eido/filters)

part of the point of this is to make it easy to access the particular endpoints for a given project, by browsing to the project page and then having those links be there, already populated for you.

**Comment by nleroy917** [comment]
Ok. That does seem useful, and also easy to implement. Should they be buttons or just links?

**Comment by nsheff** [comment]
I'd just have them be links, personally. But we can iterate on styling, do what you like for now, first get the functionality there.

**Comment by nleroy917** [comment]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/41063083/173419521-df77eb23-cc1d-4055-88a2-f3138fc4282a.png">
How do we feel about this? Still need to handle the python syntax inside the table...
