### ISSUE TITLE
Error making new PEP

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#366]
In this interface, if you paste a table, and then delete one of the columns, it gives an error when you try to add:
![image](https://github.com/user-attachments/assets/c106f26b-82ab-4b57-9963-5fdbc958f44a)

I can't take a screenshot of the error because it disappears too quickly. but it says:

Invalid sample table. Error: Empty column header detected at index 0.

**Comment by nleroy917** [comment]
Could be related to `ph_id` column stuff....

@sanghoonio What do you think about adding a prop to the `<SampleTable />` component that turns that feature on and off? In this case, its not needed since this is a new PEP being made.

**Comment by nsheff** [comment]
I again suggest not using any hidden anything on the handsontable. It is just going to lead you to confusing bugs and hours spent troubleshooting edge cases, and make the user experience bad.

**Comment by khoroshevskyi** [comment]
I am pretty sure that this issue is caused by resolving #343 . New column name is not invented, and empty column is not deleted, so it shows user that user made a mistake. @nleroy917 probably you can comment more on this topic

**Comment by nleroy917** [comment]
I agree initially, but the empty column in the screenshot is index 2, whereas the error message he reported says index 0, which doesn't make sense

**Comment by nsheff** [comment]
I was just using a placeholder. It actually said 2, if I deleted that column. I couldn't screenshot the actual error.

**Comment by nleroy917** [comment]
Ok, then this is a correct error. You've got am empty column, so its telling you to do something about it. I guess options are:

1. set to `null`,
2. set to `""`,

If a user has multiple empty columns, though, it could lead to weirdness if we are saving those

**Comment by nsheff** [comment]
I don't understand really.  There should be no difference between a table where I've pasted 2 columns, and one that I've pasted 3 and then deleted one! If there's some difference there, it's indicative of a bad practice happening where you're messing with the content before/after paste or something, which is what you should eliminate.

**Comment by nleroy917** [comment]
There should be no messing with content... your header is just blank and its telling you that it doesn't want to convert that to an object attribute (without doing something weird). If we let users save this, then the resulting the database entry would be:
```ts
samples = [{
  sample_name: 10063-28,
  barcode_index: UDI_01,
  null: null # <--- here
},
{
  sample_name: 10162023-29,
  barcode_index: UDI_02,
  null: null # <--- here
}, ...]
```
etc, etc, etc...

There are ways to sort of filter these things out, but again that will lead to odd behavior and things shifting when users hit "Save"... its a difficult operation given the stark difference in data models between `handsontable` and our database representation of a sample table

**Comment by nsheff** [comment]
Hmm. I still don't quite follow. That column was already null. It seems to me that something changed when I put data into it and then deleted it.
