### ISSUE TITLE
Fork menu is missing helper titles

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#368]
New PEP interface has nice titles for boxes:

![image](https://github.com/user-attachments/assets/3b41dc50-f65a-4981-a0c0-d07f19a5f4da)

Fork menu doesn't:

![image](https://github.com/user-attachments/assets/f738361f-7eee-4664-9f98-1213ff39712f)

The Fork menu should use the same component.

**Comment by sanghoonio** [comment]
Updated
