### ISSUE TITLE
Displaying sample attributes with multiple values

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#37]
Right now, tables are showing Python-syntax lists when there are multiple values for a given entry. 

For example, http://pephub.databio.org/pep/nfcore/demo_rna_pep/view

![image](https://user-images.githubusercontent.com/5271009/173362744-c8938b79-cef8-4b86-a5bd-9e3ba2fd8667.png)

 I think I wouldn't show embedded values like this, but think of some other way to display this.

**Comment by nleroy917** [comment]
Another way to display the entire table or display just the listed values?

**Comment by nsheff** [comment]
> Another way to display the entire table or display just the listed values?

I don't understand, sorry, is this a question?

**Comment by nsheff** [comment]
I think I understand your point now. I don't really have a prescription; just that it could probably be improved visually

**Comment by rafalstepien** [comment]
`eido validate config.yaml -s <path_to_schema.yaml> -e`

**Comment by nleroy917** [comment]
Programmatically, how would this work? This is what's going on currently:
https://github.com/pepkit/pephub/blob/d38c829c95325452627a181b059bab31b7e43faf/pephub/routers/project.py#L158

**Comment by nsheff** [comment]
Yes, you can call the same filter from within Python, just like that. You may just need to use the updated filter that solves this issue, or choose a different filter that uses the multiline output.

**Comment by nleroy917** [comment]
Not sure if this made it into the latest release?

**Comment by rafalstepien** [comment]
I'm not sure if my solution solves your problem, but I included it in latest release

**Comment by nsheff** [comment]
This is not solved. see for example:

![image](https://user-images.githubusercontent.com/5271009/204820394-d01cc975-7773-4534-83ab-d73f597852e6.png)


https://pephub.databio.org/pep/Khoroshevskyi/subsample1/view?tag=test

**Comment by nleroy917** [comment]
Is this still an issue? I can't find an example where attributes are being displayed like this

Maybe this would be an example, but it looks ok? https://pephub.databio.org/nleroy917/subsample1?tag=default

**Comment by nsheff** [comment]
this is solved by no longer showing rendered samples, but tables -- including subsample tables.
