### ISSUE TITLE
Organizations you belong to should show on org pages

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#374]
This is nice on my personal page:

![image](https://github.com/user-attachments/assets/4003c261-f6e2-4519-9fe1-45d6aaa454a3)

Why doesn't it show on the org pages?

![image](https://github.com/user-attachments/assets/5495062e-9817-43b0-a638-517df4c2b96f)

**Comment by nsheff** [comment]
This seems like an easy one for @sanghoonio

**Comment by sanghoonio** [comment]
Updated: 
![image](https://github.com/user-attachments/assets/81a19c8d-9e71-4319-8401-9ab388cc26d0)

**Comment by nsheff** [comment]
I mean show links to the other organizations. the point is for navigation. It should say "Organizations you belong to: ..." with links to the other organizations.

**Comment by sanghoonio** [comment]
I feel keeping the conditional text for organizations you belong to can be helpful:
![image](https://github.com/user-attachments/assets/3067ee3d-0e28-4568-99b6-a05c17c7313b)
![image](https://github.com/user-attachments/assets/a639f018-820c-4c2d-81dd-6a036c589920)
