### ISSUE TITLE
Removing 'name' from config yields unknown error

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#375]
Steps to reproduce:

- go to any pep
- click on config tab
- remove the 'name: ...' entry
- click 'save'

It will say "Unknown error occured".

**Comment by nsheff** [comment]
Just to add some info to this:

- `name` is not a requirement in the pep spec, and the local peps work fine with out it.
- either way, this error message should be smarter.

**Comment by sanghoonio** [comment]
![image](https://github.com/user-attachments/assets/7d05cfa0-55ee-4b91-8c04-4e02a5c410ba)

Does this work? This is a client only change since local peps don't need the 'name' value.
