### ISSUE TITLE
Trying to view subsamples while in history mode causes error

### ISSUE THREAD

**Issue by sanghoonio** [pepkit/pephub#379]
To replicate: open a project with no subsamples and go into history view. Attempt to view the subsamples tab. Or, open a project and go to the subsamples tab. Attempt to go into history view. The page will crash.

I guess the solution for now is to disable the subsamples tab if in history mode, and if in the subsamples tab when entering history mode, go to samples tab?

**Comment by nsheff** [comment]
But wait -- why? Why are subsamples not compatible with history?

The solution is probably to fix the big. It seems like this is probably a small bug, since I can't think of a reason why it shouldn't work fundamentally
