### ISSUE TITLE
Simplifying main landing page

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#39]
Two suggestions:

1. The main landing page could show the list of Namespaces shown here: http://pephub.databio.org/pep/view -- I don't really think this needs to be a separate page.
2. These would be more concise in a table, instead of full-screen-width cards.

**Comment by nleroy917** [comment]
Should be much better with the latest commits

**Comment by nsheff** [comment]
what's needed to deploy this, so it's live on the demo server?

**Comment by nleroy917** [comment]
Was working through the rest of the milestones. I can push and deploy the dev branch now so it can be tested
