### ISSUE TITLE
Sample names with slashes break endpoints

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#40]
Not sure what to do about this. It is probably a low priority, but sample names from GEO PEPs sometimes have slashes in them (`/`) and that breaks the functionality of the sample endpoints.

e.g. 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/41063083/173894725-b846043a-fc76-4737-a68f-eaf309112600.png">

**Comment by nsheff** [comment]
probably need to sanitize sample names from geo. maybe that's an option geofetch could do. also shouldn't have spaces in sample names.
