### ISSUE TITLE
Cannot upload PEP from the add menu

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pephub#407]
If I simply download a pep from pephub and then try to create a new pep via uploading the csv + config, I see an  "unknown error has occurred".

It is this workflow:
![image](https://github.com/user-attachments/assets/72a9b557-fba2-4bfa-a665-19c1ace9624a)

**Comment by khoroshevskyi** [comment]
This happens, because user didn't provide any schema, so we have to make sure it doesn't fail

**Comment by khoroshevskyi** [comment]
Actually, the error is that UI return `undefined` instead of schema registry path:
```
pepdbagent.exceptions.RegistryPathError: Provided registry path is incorrect. Error in: 'undefined'
```
