### ISSUE TITLE
New `PepAgent` removes ability to serve configuration files

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#43]
Maybe this is an issue for `pepdb`, but originally it was quite easy to serve a config file for any PEP since the actual files were stored next to the server. Now that we are migrating to the database representation of PEPs, it is not so trivial to serve config files through the API.

What can we do to retain the file-serving capability of pephub? Some ideas:

1. Store binaries in the postgres database
2. Reconstruct the config file on pephub using `peppy`
3. Store files somewhere else?

**Comment by nleroy917** [comment]
Thinking more, we could probably use `eido` to just recapitulate the configuration file by leveraging the `yaml` filter. This lives at the `/pep/{namespace}/{project}/convert` endpoint

**Comment by nsheff** [comment]
at the time, the pepdb was storing processed peps.

Now, it's storing unprocessed peps, so you should have access to the original config.

**Comment by nleroy917** [comment]
This is solved with new updates to `pepdbagent`
