### ISSUE TITLE
API endpoint semantics for PEP tags?

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#45]
With the new tag schema [changes](https://github.com/pepkit/pephub_db/pull/24), how do we want to handle separate **tags** for PEPs, say `demo/basic:latest`? I was thinking maybe `/pep/demo/basic/latest`? but I am not really sure. Colons (`:`) are invalid characters in URIs. I'm not sure how dockerhub handles this...

@nsheff thoughts?

**Comment by nleroy917** [comment]
Will be solved with next release.

**Comment by nsheff** [comment]
Hmm sorry I never wrote on this. I'd use query parameters for tags, since they are optional. So, that's like `?tag=...`

**Comment by nsheff** [comment]
If this was finished with 0.3.0, do you want to note this new feature in the changelog?

**Comment by nleroy917** [comment]
Sure
