### ISSUE TITLE
Add authentication to submission endpoints

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#46]
### PEP Submission
It has been discussed a lot that we should open an endpoint for submitting PEPs to PEPhub. However, it needs to involve some sort of authentication. I believe the plan is to use [Auth0](https://auth0.com/blog/build-and-secure-fastapi-server-with-auth0/) to do this. We should protect the submission endpoint to only allow authenticated users to submit a new PEP.

### What's Been Done
There are two endpoints now to help with PEP submission:
1. `GET /pep/{namespace}/submit`:
This returns a webpage with a form that user's can use to name their PEP, upload files, and add a tag. I believe the idea is the _username_ of the user will be used to populate the namespace.

2. `POST /pep/{namespace}/submit`:
This accepts a `multipart/form-data` `POST` request and utilizes the submission to insert a new PEP into the database using `pepdbagent`. At present, this is only available if their is a `SERVER_ENV=development` environment variable set when running the server.

### What Needs To Be Done:
1. Use authentication to only permit the use of these endpoints for authenticated users (through GitHub).
2. Utilize the authentication information to populate the submission form.

I am assigning this to @nsheff since he has experience with Auth0 and `next.js` deployment. @rafalstepien since you are familiar with Django, I thought I'd assign you too as you may have insight here.

I am close to another release of `pephub`, so once that is done, I think we can start to work on this.

**Comment by nsheff** [comment]
I guess a first iteration on this is done and released in `0.3.0`
