### ISSUE TITLE
Disable hard querying requests

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#48]
I was checking how does pephub works, and I think we should disable hard querying requests, e.g. get all projects, or similar queries. We will have a lot of errors there and it can cause server overload. 
One cause of this issue is loading projects to peppy itself.

I would suggest:
1) https://github.com/pepkit/pepdbagent/blob/5d60659c4f7cfca0034aac29fe8a0c4ad708f841/pepdbagent/pepdbagent.py#L404-L421  -- disabled this function forever, LOL. pepdbagent won't handle so much projects.
2) https://github.com/pepkit/pepdbagent/blob/5d60659c4f7cfca0034aac29fe8a0c4ad708f841/pepdbagent/pepdbagent.py#L317-L402  -- for this 2 functions we should set limits.

Looking for discussion on this issue
@nsheff @nleroy917

**Comment by nsheff** [comment]
I agree.

For the second, I suggest using adding `limit` and `offset` parameters to these functions, and then probably setting a maximum value for the limit parameter, maybe at 10k.

**Comment by nsheff** [comment]
@Khoroshevskyi is this finished? can you update this issue?

**Comment by khoroshevskyi** [comment]
> @Khoroshevskyi is this finished? can you update this issue?

In pepdbagent - yes, but I don't know about pephub

**Comment by nleroy917** [comment]
This is addressed in #72 and will be fixed via #80
