### ISSUE TITLE
PEP v1 support

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#5]
@nsheff I noticed that when hitting `/v1/ChangLab/PEP_1` you get an internal server error as the PEP isn't compatible with `PEP 2.0.0`:

```
NotImplementedError: The attribute implications section (implied_columns) follows the old format. 
Reformatting is not implemented. 
Edit the config file manually (add 'sample_modifiers.imply') to comply with PEP 2.0.0 specification:
http://pep.databio.org/en/latest/specification/#sample-modifier-imply
```

Is there an incentive to support both versions of PEP? As well, how would that be implemented?

**Comment by nsheff** [comment]
No. Just ignore the v1 PEP, it's deprecated. That's the point is that we have PEP 1.0 and PEP 2.0 version in there. just use the 2.0 version.
