### ISSUE TITLE
Allow PEPs to be marked private

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#51]
Right now, any uploaded PEP is publicly visible. Instead, a user should be able to mark PEPs as public or private. 

As a simple permission system to start: 
- A private PEP in an organization namespace should be visible to members of that organization
- A private PEP in a personal namespace should be visible to only that person

To do this will require:
- [x] Database flag to store public or private status of each PEP (a column in the DB?)
- [x] Endpoints to set/get this status
- [x] Update public interface to only show public PEPs
- [x] PEP list endpoints should only show public PEPs for unuthenticated users
- [x] All data retrieval endpoints should only allow public for unauthenticated users (using access control decorators), but allow logged in users access to their own
- [x] UI to set this status on an edit page of some kind.

**Comment by nsheff** [comment]
@rafalstepien can you check and flag this issue as you finalize this?

**Comment by nleroy917** [comment]
Related to #52 . All of this gets addressed in the l latest release `v0.5.0` #80
