### ISSUE TITLE
Incorrect links to PEPs and incorrect name of the project 

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#55]
- [ ]  PEPhub has incorrect name of the project on the project website. e.g. `https://pephub.databio.org/pep/geo_recent/GSE179805/view?tag=raw`

![image](https://user-images.githubusercontent.com/41573628/199794162-0ad50535-0a33-4b86-b449-9b26c1877432.png) 

- [ ] PEPhub has incorrect links to the PEP data. because tag is not added. e.g. :
- [/pep/geo_recent/None](https://pephub.databio.org/pep/geo_recent/None)
- [/pep/geo_recent/None/samples](https://pephub.databio.org/pep/geo_recent/None/samples)
- [/pep/geo_recent/None/subsamples](https://pephub.databio.org/pep/geo_recent/None/subsamples)

![image](https://user-images.githubusercontent.com/41573628/199794882-3cd26e81-fda3-4aab-a054-38ab295229b3.png)

**Comment by nleroy917** [comment]
I believe that this is all fixed in #80
