### ISSUE TITLE
Bug in renewed log in on PEPhub

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#57]
After one day of using PEPhub as loged in user tocken is expiring. After that page is not working: error pops up:
```
{"detail":"The token has expired, please log in again."}
```

**Comment by nleroy917** [comment]
Is this a bug? I wonder if this is intended behavior. Regardless, pephub should now prompt you with proper error codes when you fail authentication **or** authorization.

**Comment by khoroshevskyi** [comment]
I checked it few days ago, and when tocken was expired, pephub just showed this message. I think It should redirect user to login page.

**Comment by nleroy917** [comment]
A reproducible example would help.

**Comment by khoroshevskyi** [comment]
I can reproduce it only if I will be running server all day, that's why on local server it's hard to reproduce.
I will try to explain:
This situation happens when you are logged in several hours, or days. Then you go to the pephub main page an get message above. Just error. With no possibility to log in again or use pephub without authentication.
![image](https://user-images.githubusercontent.com/41573628/214088534-b7eb7826-097e-4f9c-af64-405de3a05046.png)

**Comment by nleroy917** [comment]
I will investigate this. My idea is that we can wrap something in a `try: catch:` and redirect to the `/login` route.

**Comment by nleroy917** [comment]
I just got this.. had to delete my cookies for pephub to fix it. We definitely need to add a `try: catch:` to just delete or request the cookie of the token has expired... GitHub has an 8 hour expiration time on JWTs so, to reproduce you need to login to pephub, then wait 8 hours and observe the error.

**Comment by nleroy917** [comment]
Luckily, I think it's an easy fix. We just need to alter [this line](https://github.com/pepkit/pephub/blob/571ffed256dbfac63b2f6d772948be7cb5066f93/pephub/dependencies.py#L122) to include an expiration time for the cookie. It's detailed in this [FastAPI issue](https://github.com/tiangolo/fastapi/issues/2268).

`session_info` should come back with an expiration date/time.

**Comment by khoroshevskyi** [comment]
@nleroy917, I have fixed it in this commit: https://github.com/pepkit/pephub/commit/46cdd1d63ef445e61b26f1c1226df0bc00ed6445

**Comment by nleroy917** [comment]
We should probably do two more things. The first is also just set the expiry for the token when it's set. This is what we are currently doing:

```python
response.set_cookie(
    "pephub_session", 
    session_info_encoded
)
```
I think it should be changed to:
```python
response.set_cookie(
    "pephub_session", 
    session_info_encoded,
    expires=session_info["exp"] # <--- something like this
)
```
The second is just delete the token by setting to `None` if we get a `jwt.exceptions.ExpiredSignatureError` but setting it to None. Maybe something like:
```python
except jwt.exceptions.ExpiredSignatureError:
    pephub_cookie.set(None) # <-- is this possible?
```

@Khoroshevskyi if you want to implement this, let me know

**Comment by nleroy917** [comment]
Testing this with manually-set expiration times of 10 seconds, it seems to work.

**Comment by nleroy917** [comment]
This should be fixed in the latest release
