### ISSUE TITLE
missing .env file?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#59]
Following instructions for local development:

```
docker compose up --build
open /home/nsheff/code/pephub/.env: no such file or directory
```

**Comment by nleroy917** [comment]
The `.env` file holds secrets like the database username and password, and some configuration settings.

Naturally, it's not checked in to github. Its a file that should be curated by the person running the code.

**Comment by nsheff** [comment]
OK -- for development, how am I supposed to run a test instance?

Shouldn't you provide a generic one so I can run `docker compose up` and do some development?

**Comment by nsheff** [comment]
And even if not, there needs to be some documentation of what I'm supposed to do to run it

**Comment by nleroy917** [comment]
Ok. We can provide an example `.env` file in the documentation if needed. We can also write a script that creates it if needed, but it is trivial. I just don't want to check in `.env` since it has secrets. It would look something like:

```
POSTGRES_HOST=localhost
POSTGRES_DB=pephub
POSTGRES_USER=docker
POSTGRES_PASSWORD=password

GH_CLIENT_ID=...
GH_CLIENT_SECRET=...
REDIRECT_URI="http://localhost:8000/auth/callback"

SERVER_ENV=development   
```

**Comment by nsheff** [comment]
but for a development environment, shouldn't this come with dummy database that the docker-compose is going to set up? it's ephemeral so it doesn't matter, it just has to be something so I can run a blank slate

**Comment by nleroy917** [comment]
Yes. There is an `examples/` directory. The idea is the user can load the database with these PEPs using a provided script - if that makes sense.

The scripts: https://github.com/pepkit/pephub/tree/master/scripts

**Comment by nsheff** [comment]
The point I'm trying to make is: I should be able to read the README, and within a few minutes, have a local development instance running. I haven't been able to do that. 

Ideally it should take just a few commands to get a development instance running. And, that should be in the README.

**Comment by nleroy917** [comment]
Ok. These are the steps for development:

1. Curate a `.env` file (we can provide an example)
2. Run `docker compose up --build`
3. Run a database loading script (these will persist between stops and starts)

I can add these steps to the README. I think throughout iterations of pephub, the documentation might have gotten out of sync. Is anything too complex for a development user? We can try to simply them if needed

**Comment by nsheff** [comment]
Ok I think we're on the same page. Just to be sure: I think the example env could start with some dummy credentials that set up a basic database in the docker compose that I can use locally. So, I shouldn't have to curate the env if I'm just trying to launch a basic instance that's empty or with some dummy data. It should already be set up to do that.

**Comment by nleroy917** [comment]
Do you mean having an env file already in the repository for a new user? If so, I am fearful of checking in credentials on accident. The gitignore lists `.env` especially to avoid that scenario.

We could have a `.env.example` file maybe and point to that for `docker compose`.

```yaml
version: '3.8'

services:
  server:
  ...
    env_file:
      - ./.env.example # <----- here
  ...
```

That feels more safe to me. Sometimes it's nice to look at the deployed database on AWS, so maybe if one desires, they can add their own `.env` and change the compose file. Is that a good workflow?

**Comment by nsheff** [comment]
>  Is that a good workflow?

Yes

**Comment by nsheff** [comment]
PS -- I'd advise not storing credentials in plain text *anyway*, even if you `.gitignore` them. One way to do this is using [pass](https://www.passwordstore.org/).

You are kind of doing this in the non-docker version with the environment variables for `POSTGRES_USER`, etc.

**Comment by nleroy917** [comment]
I've tried hard to improve documentation. It will be pulled in with `v0.5.0` release via #80
