### ISSUE TITLE
validating multi-file peps

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#61]
This function assumes that every file uploaded is a PEP:

https://github.com/pepkit/pephub/blob/cb109b697020ae031c10f3f3cfaf1e14ab328ca6/pephub/routers/eido.py#L185-L190

It creates a Project object from each file. This is false, many PEPs are made up of multiple files.

This means the validation will only work for single-file PEPs.

**Comment by nsheff** [comment]
Hi @aliparslan just following up on this issue, will you be able to take a look at this soon? thanks

**Comment by nleroy917** [comment]
I think that this actually works now with the latest UI.

<img width="1186" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/8d207ec1-c944-47fd-8799-6cb81c71b306">
