### ISSUE TITLE
Infrormation about last project update date

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pephub#66]
It would be nice to add last update date to the project info info on the page.
Here: 
![image](https://user-images.githubusercontent.com/41573628/205394193-b7ba7ebf-4d5a-4e53-8f30-dbed52425bac.png)

**Comment by nleroy917** [comment]
This is working and should be solved with `v0.5.0` release #80

**Comment by khoroshevskyi** [comment]
This issue was solved in v0.5.0
