### ISSUE TITLE
Ability to star/favorite PEPs

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#74]
I think that it would be cool to be able to star or favorite a PEP like on GitHub. This could maybe be information stored at the namespace level - which PEPs a namespace has starred?

This is more of a `pepdbagent` task

**Comment by nleroy917** [comment]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/41063083/207650423-a3e1ef4a-6588-4406-9fe6-a8fbce8dd62d.png">

**Comment by khoroshevskyi** [comment]
In this case we should think about restructuring database, or adding additional columns (user table)

**Comment by khoroshevskyi** [comment]
If the pephub will be continuously growing, in some point we will have to do it

**Comment by nleroy917** [comment]
Would be great too if we could bring in `num_stars` or `num_favorites` with a PEP's annotation. Then we can render UI's like GitHub: 
<img width="955" alt="image" src="https://github.com/pepkit/pephub/assets/41063083/8cd542de-800c-4045-b52b-f38122818d82">

**Comment by nleroy917** [comment]
This is mostly implemented across all relevant packages

**Comment by khoroshevskyi** [comment]
This issue was solved in v0.11.0
