### ISSUE TITLE
streamline database setup

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#81]
In step 1 of the readme ("Database Setup"), it has you run `sh setup_db.sh`

```
sh setup_db.sh
docker pull postgres
docker build -t pephub_db postgres/
docker run -p 5432:54432 pephub_db
```

The content of `setup_db.sh` is:

```
#!/bin/bash
mkdir -p postgres
curl "https://raw.githubusercontent.com/pepkit/pepdbagent/pep_db/Dockerfile" > postgres/Dockerfile
curl "https://raw.githubusercontent.com/pepkit/pepdbagent/pep_db/pep_db.sql" > postgres/pep_db.sql
echo "\nVOLUME ./postgres/volumes/ /var/lib/postgresql/data" >> postgres/Dockerfile
```

This is entangling the two repos in a way that feels sub-optimal.

1. Would it make more sense to put these Dockerfile and pep_db.sql into the pephub repo?
2. would it make more sense to move the "construct a database" README directions into the pepdbagent repo?
3. Would it make more sense to write documentation that spans the two repos (and therefore expects that you would have cloned both repositories, instead of just the pephub one thereby requiring  curl out to the pepdbagent repo?)

I like the idea of having pepdbagent be just a tool and not require cloning. this would argue for point 1 above, rather than point 2 or 3.

**Comment by nsheff** [comment]
Case in point: when I tried to run this, I got:

```
docker build -t pephub_db postgres/
Sending build context to Docker daemon  3.072kB
Error response from daemon: dockerfile parse error line 1: unknown instruction: 404:
```

This would be highly confusing to me at this point, since I haven't been shown in the tutorial that this `.sh script is actually curling something. But anyway, turns out: that's a bad URL.

```
cat postgres/Dockerfile 
404: Not Found
VOLUME ./postgres/volumes/ /var/lib/postgresql/data
```

So, no wonder the Dockerfile doesn't work...

**Comment by nleroy917** [comment]
This has been something that has occupied my mind since starting... i don't know. On one hand since they are so coupled, it makes sense to place the database schema in pephub for deployment. but on the other hand `pepdbagent` will crash immediately if the database schema is wrong, so it also makes sense to place it there. I don't know the solution, and for now, this is what I came up with. 

I think the schema definition should only live in one place, however.

**Comment by nleroy917** [comment]
If it were myself doing all of this solo, I'd have `pepdbagent` **create the schema** if it doesn't exist - not just fail. Therefore you need only supply a fresh postgres database. If a `projects` table already exists, maybe then we can raise an error, but I think if you give `pepdbagent` a connection to a postgres instance, it should 1.) connect then, 2.) check if there is a `projects` table and if it doesn't exist, create it. Does that seem reasonable? Flow chart:

```mermaid
graph LR
  A[connect to db] --> B{projects table exists?}
  B -- No --> C[Create with correct schema]
  C --> F[Success. continue]
  B -- Yes --> D{Schema is correct?}
  D -- No --> E[Raise error]
  D -- Yes -->F
```

This way, the schema and instantiation of schema responsibility lies solely with `pepdbagent`

**Comment by nleroy917** [comment]
Another option here is to have a `databio/pephubdb` docker container with the schema already created inside? I agree the database setup needs to be easier still.

**Comment by nleroy917** [comment]
@Khoroshevskyi is it possible to implement the above flow in `pepdbagent`? That would help people get started with pephub, I think.

**Comment by nleroy917** [comment]
This still would be nice and would make it a lot easier to deploy PEPhub to places like fly.io and heroku

**Comment by nleroy917** [comment]
This issue might need to live over at pepdbagent. @khoroshevskyi said that the new `pepdbagent` has a `create_schema` function, so that should be called in the above chart

**Comment by nleroy917** [comment]
@khoroshevskyi demonstrated that this is now fixed with the new `pepdbagent`. Documentation should be updated to reflect this and remove any database configuration instruction.

**Comment by nleroy917** [comment]
Documentation is updated for this. It's changed to:

~~### 1. Database Setup~~

~~_pephub_ is backed by a [postgres](https://www.postgresql.org/) database to store PEPs. You can easily create a new pephub-compatible postgres instance locally:~~


### 1. Database Setup

_pephub_ is backed by a [postgres](https://www.postgresql.org/) database to store PEPs. You can easily create a new pephub-compatible postgres instance locally:

```
docker pull postgres
docker run \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=docker \
  -e POSTGRES_DB=pep-db \
  -p 5432:5432 \
  postgres
```
