### ISSUE TITLE
Page display is not loaded smoothly, blinking a different look 

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#84]
When I load a page, it first flashes something and then css seems to kick in, yielding the final rendered page. 

We need to track down what's causing this split second delay and eliminate that so that the pages appear to load smoothly.

**Comment by nleroy917** [comment]
Is this any page? Could it be all the `.js` we are loading in? Monaco editor, handsOnTable, papa parse, bootstrap, etc

**Comment by nsheff** [comment]
Maybe we need to move the css before the javascript.

**Comment by nsheff** [comment]
It's pretty clear to me after further investigation that it's loading content, rendering it, and then updating it when the css loads. So there's too much delay in loading the css, it needs to be prioritized.

**Comment by nsheff** [comment]
That solves it in my hands

**Comment by nleroy917** [comment]
Great. I'll try it out

**Comment by nleroy917** [comment]
This seems fixed for me too, locally
