### ISSUE TITLE
Create a new PEP without uploading any files? 

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#85]
>  > [ ] Should it be possible to create a new PEP without uploading any files? Like, start from a blank PEP and then just edit it. I would like to create a new PEP from scratch.

> I agree. Maybe when we port to react 😎

_Originally posted by @nleroy917 in https://github.com/pepkit/pephub/issues/80#issuecomment-1413032139_

I actually think this is a really important feature, and it should be really easy to do. All we would need is a button "new" that would create a blank PEP in the database, and then forward you to the edit screen.

This would make it much easier to try out the system, and not even have to deal with any files.

**Comment by nleroy917** [comment]
Good idea - this is rather simple.

```javascript
fetch(
  {namespace}/projects,
  method="POST"
  body=JSON.stringify({
    config_yaml: "",
    sample_table_csv: ""
  })
)
.then( () => ..redirect)  
```

Something like this.

**Comment by nleroy917** [comment]
I've added this functionality.

**Comment by nsheff** [comment]
:tada: I'm super excited about this one!

**Comment by nleroy917** [comment]
This was addressed in the latest release
