### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#86]
Latest error:

```
[INFO] [11:25:01] Initializing connection to pephub...
[INFO] [11:25:01] Connected successfully!
Traceback (most recent call last):
  File "/usr/local/bin/pephub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/pephub/main.py", line 105, in main
    uvicorn.run(
TypeError: run() got an unexpected keyword argument 'debug'

```

**Comment by nsheff** [comment]
It looks like `debug` may have been removed in a recent update to uvicorn.

Did we also update uvicorn in this release? 

https://github.com/encode/uvicorn/blob/master/CHANGELOG.md

**Comment by nsheff** [comment]
This PR talks about removing the CLI `--debug`... it doesn't say anything about the `debug` argument to the `run` function, but maybe they are related?

https://github.com/encode/uvicorn/pull/1640

**Comment by nleroy917** [comment]
I forgot that we deploy using the cli entry point not the standard `uvicorn pephub.main`.

It's possible. The `cli` interface to pephub has definitely been neglected

**Comment by nleroy917** [comment]
We arnt pinning `uvicorn` to a version so if they updated it to not include debug as a `kwarg` then that makes sense

**Comment by nsheff** [comment]
Is this something you can correct this morning?

**Comment by nleroy917** [comment]
Attempting now.

**Comment by nleroy917** [comment]
I think this is now solved with the latest release and DNS configurations.
