### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by shbrief** [pepkit/pephub#87]
Hi! When I try to run the container, I got this error:
`pephub-server-1  | AttributeError: 'BaseConnection' object has no attribute 'pg_connection'`
Does anyone have a solution to this error? Thanks!

**Comment by nsheff** [comment]
I also saw this problem before... I am trying to remember what it was indicating...

**Comment by nleroy917** [comment]
Hi, @shbrief it looks like you might be running with `docker-compose`? If so, it expects a `.env` file specifying the connection to your database.

I'm able to reproduce this l locally, so I will try to fix it as provide steps to fix!

**Comment by shbrief** [comment]
Thanks,@nleroy917! I tried both options, standalone `docker` and `docker compose`, and both of them give the same error. I used the `template.env` as `.env` without any modification/update, FYI. 

For now, I'm just trying pephub without any specific database in mind, so it would be good to have anything that runs. :)

**Comment by nleroy917** [comment]
@shbrief I did some digging/testing, and I have two questions:

1. Are you running this on an M1 mac?
2. What does the error upstream look like?

I was able to test this on an M1 and reproduce this with two results. The first being an upstream error of `psycopg2.OperationalError: connection to server at "db" (172.19.0.2), port 5432 failed: FATAL:  database "pep-db" does not exist`, and the second being an upstream error of `psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above`.

### SCRAM Authentication Error
The SCRAM authentication error [seems to be related to Apple silicon](https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1898). To resolve this, you can run the build [using rosetta](https://docs.docker.com/desktop/install/mac-install/) by exporting the following:
```
export DOCKER_DEFAULT_PLATFORM=linux/amd64
``` 

Then retrying the build:

```
docker compose up --build
```

This will probably significantly increase your build time, however 😕 An alternative could be for us to replace the `psycopg2-binary` dependency with plain `psycopg2`, but that's pulled in from the [helper package `pepdbagent`](https://github.com/pepkit/pepdbagent).

### Connection Error
This is just a result of having improper credentials. I believe the latest `template.env` file should have the proper connection settings. I tried to [update our README](https://github.com/pepkit/pephub#option-2-docker-compose) to be even more straightforward for a `docker compose` setup by including the following command:
```
cp environment/template.env .env
```
I'd just verify the contents of `.env` around the postgres settings look like:

```
POSTGRES_HOST=localhost:5432
POSTGRES_DB=pephub
POSTGRES_USER=docker
POSTGRES_PASSWORD=password
```

Let me know if any of this helps, and we can keep working to resolve the issue if not!

**Comment by shbrief** [comment]
@nleroy917 Thanks for your help!
1. Yes, I'm running this on an M1 Mac.
2. There were two more errors upstream: `psycopg2.OperationalError: could not translate host name "localhost:5432" to address: Name or service not known` and `AttributeError: 'PEPDatabaseAgent' object has no attribute '_PEPDatabaseAgent__con'`

After I ran `export DOCKER_DEFAULT_PLATFORM=linux/amd64`, I could run _pephub_ at `http://localhost:8000`! :)

One follow-up question is. how can I link my GitHub account? **_Login with GitHub_** button gives me a 404 error. I guess I should set it up in my `.env` file? What is the `GH_CLIENT_SECRET`?

**Comment by nleroy917** [comment]
I'm glad you got it working! So the `export DOCKER_DEFAULT_PLATFORM=linux/amd64` removes those errors you saw upstream?

As for the github authentication - that's a great question, and maybe the documentation can be more clear. If you want to be able to authenticate with GitHub while running your **own server locally**... you'd have to [setup a Github OAuth application](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app). 

It's actually pretty easy. You'd just need to be specific with **step 8: type the callback URL of your app.** You'd want this value to be `http://localhost:8000/auth/callback`. Then you can populate your `.env` file with the subsequent `client-id`, `client-secret`, and `redirect-uri` you are given. Something like:

```
# other variables
GH_CLIENT_ID=<my-personal-apps-client-id>
GH_CLIENT_SECRET=<my-personal-apps-client-secret>
REDIRECT_URI=http://localhost/auth/callback
```

@nsheff might be able to weigh in here. I think it would be useful to make documentation for this. Further, I wonder how we can check that a server has been configured with a valid `client-id` and `client-secret` such that we could toggle the login button to disabled if not and provide some feedback there.

**Comment by nleroy917** [comment]
@shbrief I've [added some documentation](https://github.com/pepkit/pephub/blob/master/docs/authentication.md#setting-up-github-oauth-for-your-own-server) for setting up your own GitHub OAuth app. Let me know if that gets things working for you to authenticate with GitHub!

**Comment by shbrief** [comment]
@nleroy917 Now my _pephub_ is linked to my GitHub account! :) 
If I want to add my own PEP, I should upload both the Project config file (yaml) and sample table (csv) at the same time? 

p.s. I'm not sure whether it's ok to keep asking a follow-up question here. Let me know if you want me to open a new issue.

**Comment by nleroy917** [comment]
Great! Yes, a PEP is represented by the combination of both files. Just drag them in, and it should be able to parse and insert into the database.
