### ISSUE TITLE
The GitHub app that supports authentication should pull private organizations.

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub#89]

**Comment by khoroshevskyi** [comment]
I found the problem, but didn't fully fix it. Instead of using `https://api.github.com/users/USERNAME/orgs`we should use: https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#list-organizations-for-the-authenticated-user

I have changed it and added orgs to scopes for OAuth Apps. It should had fixed the problem, but unfortunately I am getting empty list.

**Comment by nsheff** [comment]
This may not be possible using the way we're currently doing it, because pephub is a github app, and github apps apparently don't have access to the endpoint that lists private orgs.

**Comment by nleroy917** [comment]
I think that this might be it: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps

Maybe if we specify the `read:org` scope, we will get them pulled in. this should occur when we build the authorization URL [here](https://github.com/pepkit/pephub/blob/571ffed256dbfac63b2f6d772948be7cb5066f93/pephub/helpers.py#L158)

**Comment by nleroy917** [comment]
Oh I see this was done.

**Comment by nleroy917** [comment]
I'm wondering if this is unfixable

**Comment by nleroy917** [comment]
Status of this? I dont think this is possible to control unless the user specifically marks their membership as no-private. Creating a personal access token and hitting the `orgs` endpoint yields only `databio` and `pepkit`:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GH_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/users/nleroy917/orgs | jq
[
  {
    "login": "databio",
    "id": 13696008,
    "description": "Solving problems in computational biology"
  },
  {
    "login": "pepkit",
    "id": 29280461,
    "description": "Standardized sample metadata structure for biological research"
  }
]
```

Those also happen to be the only two orgs I have marked as non-private. My suggestion is to add some UI element to pephub that says something like:

> "Dont see your organization? Make sure you've marked it public!" 

With a link to instructions for changing your visibility.

**Comment by ayobi** [comment]
The UI element was added in 0.9.x
![image](https://github.com/pepkit/pephub/assets/17304717/a35e1d56-4a92-41bc-a595-dd04cfdc2abe)

**Comment by nleroy917** [comment]
This is unfixable, so I am closing
