### ISSUE TITLE
Database should store samples individually

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#92]
Right now, the database stores Project objects in a table.

Instead, it would be more flexible to split samples and projects into separate tables, and link them. Then, updating a sample wouldn't require updating the entire project.

**Comment by nsheff** [comment]
This will also require changing the sample editing interface to no longer "Save" after edits, but to send requests on-the-fly. Otherwise, it negates the benefits of storing samples individually.

**Comment by nsheff** [comment]
In addition, the PEP project representation will need to be paged.  

Basically, we need to add the `items`, `offset` `limit` concept to the samples *within a pep*. This will allow us to accommodate peps with thousands of samples more easily.

The endpoints that return a project with samples would then return paged samples.

**Comment by nleroy917** [comment]
Still needs done, and might be too big to bring into the scope of `v0.8.0`. It also might need changes to `pepdbagent`, right?

**Comment by nsheff** [comment]
Database now splits samples into a separate table, as of release 0.9.x
