### ISSUE TITLE
Web-based metadata builder UI

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#94]
Right now PEPhub already has a basic metadata editor UI implemented, where users can see their sample table in a spreadsheet and edit and save things.

It would be great if this editor could be extended to include validation. So, users could right there from their table editor click a "validate" button to make sure they're entering things correctly. It could also validate on save, and prompt if something invalid was entered.

This would require linking the PEP to a particular schema, or maybe set of schemas, in some way. This information could be managed in the "metameta" area, or whatever we called it -- the database-stored information surrounding the PEP.

In fact I think this advance would not be too hard to implement and would be really useful.

**Comment by nleroy917** [comment]
I believe that it sort of [does this presently](https://github.com/pepkit/pephub/blob/571ffed256dbfac63b2f6d772948be7cb5066f93/pephub/routers/api/v1/project.py#L92).  I think the error handling on the UI could be **vastly** improved as well as user feedback for errors, but it will error out and return a `400` code if the updated project fails validation with the [basic PEP schema](http://schema.databio.org/pep/2.0.0.yaml).

**Comment by nleroy917** [comment]
**I've built the basics of a UI that will let you validate your PEP as you edit it. This is just for basic PEP schema...**

![validation](https://user-images.githubusercontent.com/41063083/223219966-07efb9f9-5ba3-4ac0-8edf-fe08c8132e77.gif)

**Comment by nleroy917** [comment]
There is a lot that could be done here... but I might leave it at this for this release.

**Comment by nsheff** [comment]
agreed, that looks great for now!

**Comment by nleroy917** [comment]
Mockup for some more "builder" type functionality. Or just check any PEP you come across:

https://user-images.githubusercontent.com/41063083/232845295-4e5ea127-7079-47c6-a1cd-951556bd0166.mov

**Comment by nleroy917** [comment]
How are we feeling about the state of this issue? The builder UI is pretty robust now with validation

**Comment by nsheff** [comment]
I like it

**Comment by nsheff** [comment]
I think this is solved.
