### ISSUE TITLE
Switch deployment strategy to use new env management

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#97]
We should adjust the setup instructions to use 

```
source environment/production.env
```

Or: 

```
source environment/dev.env
```
As the recommended way to set up the env vars.

**Comment by nleroy917** [comment]
This only works for native deployment (`uvicorn`) and python deployment (`pip install`), right? Docker deployment requires you specify a `.env` file, since it doesn't have access to the host machines `env`. Is there a way to just supply docker with all the host machines `env` variables? Is that a security issue?

**Comment by nsheff** [comment]
Well, you can just set up docker to pass the necessary variables with `--env` -- is there a reason this wouldn't work for you?

**Comment by nleroy917** [comment]
Yeah, that works you are correct. It's just cumbersome to list out a bunch of `env` variables on the CLI

**Comment by nsheff** [comment]
true. but it's also cumbersome to put all the decryption capability into the container. 

If docker deployment requires an `.env` file, how will it decrypt it? The only way to make it less cumbersome is to keep the secrets unencrypted at rest, which wouldn't be ideal

**Comment by nsheff** [comment]
you could write a short script with the docker deploy command that would work with this method. It would not be very difficult, it would be something like `docker_deploy.sh`

```
source .../production.env
docker run ...
   --env POSTGRES_DB \
  --env POSTGRES_HOST \
  ...
```

Then you'd deploy it with `./docker_deploy.sh`.
Or, maybe the source would be outside of the script, so you'd first source, and then run `docker_deploy` instead of uvicorn.

**Comment by nleroy917** [comment]
I think the `env` files are there now, is all that's left to update documentation to reference this?

**Comment by nsheff** [comment]
That sounds right! And I guess write a `docker_deploy.sh` script, if you haven't already.

**Comment by nleroy917** [comment]
I've updated the README and added a `deploy_docker.sh` script.

**Comment by nleroy917** [comment]
This was fixed in the latest release
