### ISSUE TITLE
Next steps for validation UI

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#98]
Some ideas discussed with @aliparslan 

- [x] build a page with HTML hyperlinks to schema-specific page. Link this in the navbar or somewhere.
- [x] Change singlePEP/multiplePEPs to tabs for the different insertion types:
  - for step 1, tab options are: Upload, or Registry path
  - for step 2, tab options are: upload, registry path, and select built-in
- [x] have the validate button be type="button" and use `onclick` to load the results, rather than form submission

**Comment by nleroy917** [comment]
This needs a revisit since we are 1) Assigning schemas to PEPs, and 2) have a fresh validation UI built. i think it just needs polishing and feedback from people.

**Comment by nleroy917** [comment]
### Discussed in 06/20/2023 meeting

- Add a new option to *paste* a PEP.
- Add an example validation for a PEP.
- with new point release of `eido`, we can give feedback on this UI.

**Comment by nleroy917** [comment]
### Discussed in 06/27/2023 meeting
- make sure the UI is displaying the actual errors that were returned by the server
- The form is mildly broken (Nathan L. can fix this)
- endpoints are close, just figure out how to reconcile the `application/json` and `multipart-form` issue.

**Comment by ayobi** [comment]
The majority of these have been addressed and are in release `0.9.x`
